<script setup lang="ts">
import {onBeforeUnmount,ref,watch} from 'vue'
import {searchKnowledge,type KnowledgeResult} from '@/api/modules/knowledge'
const query=ref(''),topK=ref(5),busy=ref(false),error=ref(''),result=ref<KnowledgeResult|null>(null);let version=0,mounted=true
watch([query,topK],()=>{version++;result.value=null;error.value=''})
onBeforeUnmount(()=>{mounted=false;version++})
async function search(){if(busy.value)return;if(query.value.trim().length<2){error.value='请填写具体地点或至少2字的关键字';return}const v=++version;busy.value=true;error.value='';result.value=null;try{const data=await searchKnowledge(query.value.trim(),topK.value);if(mounted&&v===version)result.value=data}catch(e){if(mounted&&v===version)error.value=e instanceof Error?e.message:'检索失败，请稍后重试'}finally{if(mounted)busy.value=false}}
</script>
<template><main class="knowledge-search"><h1>旅行资料检索</h1><p class="hint">查找已公开资料中的原文片段，查看引用来源。当前按关键字检索，不调用模型生成回答，不消耗AI额度。</p><router-link to="/ai/chat">进入资料会话，保存与回看检索记录</router-link><section class="panel"><el-form label-position="top" :disabled="busy" @submit.prevent="search"><el-form-item label="地点或问题"><el-input v-model="query" aria-label="资料检索问题" maxlength="200" placeholder="例如：香格里拉十月、洱海骑行" @keyup.enter="search"/></el-form-item><el-form-item label="最多展示的片段数"><el-select v-model="topK" aria-label="资料片段数"><el-option v-for="n in 5" :key="n" :value="n" :label="`${n}个片段`"/></el-select></el-form-item><el-button type="primary" :loading="busy" @click="search">检索资料</el-button></el-form></section><el-alert v-if="error" :title="error" type="error" :closable="false"/><section v-if="result" data-testid="knowledge-results" aria-live="polite"><el-alert :title="result.message" :type="result.matched?'info':'warning'" :closable="false"/><article v-for="r in result.references" :key="r.chunkId" class="panel" data-testid="knowledge-reference"><h2>{{r.title}}</h2><p class="hint">原文第{{r.chunkIndex}}个片段</p><pre class="excerpt">{{r.excerpt}}</pre><div class="source-links"><router-link :to="r.documentPath">查看完整资料与更新时间</router-link><router-link v-if="r.sourcePath" :to="r.sourcePath">查看关联{{r.sourcePath.startsWith('/route/')?'路线':'目的地'}}</router-link></div></article></section><p class="hint">资料可能过时，不提供实时天气、票价或开放状态；请以实际公告为准。未找到的内容不会编造。可以调整地点和关键字再检索。</p></main></template>
<style scoped>.knowledge-search{max-width:960px;margin:auto;padding:30px 20px 60px}.hint{color:#64748b;line-height:1.8}.panel{margin:22px 0;padding:24px;background:white;border:1px solid #e2e8f0;border-radius:14px}.excerpt{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;line-height:1.9}.source-links{display:flex;gap:20px;flex-wrap:wrap}h2{font-size:20px}.el-select{width:180px}@media(max-width:640px){.knowledge-search{padding:24px 12px}.panel{padding:18px}}</style>
