<script setup lang="ts">
import {computed,nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import Pagination from '@/components/common/Pagination.vue'
import {sessionPage,createSession,sessionDetail,renameSession,deleteSession,historyPage,searchInSession,type KnowledgeSession,type HistoryMessage,type HistorySearch} from '@/api/modules/knowledgeSession'

const route=useRoute(),router=useRouter()
const sessions=ref<KnowledgeSession[]>([]),current=ref(1),total=ref(0),keyword=ref(''),listing=ref(false)
const selected=ref<KnowledgeSession|null>(null),messages=ref<HistoryMessage[]>([]),hasMore=ref(false),beforeId=ref<number>(),loading=ref(false),olderLoading=ref(false),sending=ref(false),mutating=ref(false)
const query=ref(''),topK=ref(5),error=ref(''),pending=ref<HistorySearch|null>(null),feed=ref<HTMLElement>()
const renameVisible=ref(false),renameTitle=ref(''),renameError=ref(''),renameTarget=ref<KnowledgeSession|null>(null)
const working=computed(()=>loading.value||sending.value||mutating.value)
let mounted=true,viewVersion=0,listVersion=0
onBeforeUnmount(()=>{mounted=false;viewVersion++;listVersion++;pending.value=null;messages.value=[]})
function reason(e:unknown){return e instanceof Error?e.message:'操作失败，请稍后重试'}
async function list(autoSelect=false){const v=++listVersion;listing.value=true;try{const data=await sessionPage({current:current.value,keyword:keyword.value.trim()||undefined});if(!mounted||v!==listVersion)return;sessions.value=data.records;total.value=data.total;if(!data.records.length&&current.value>1){current.value=Math.max(1,data.pages);await list();return}if(autoSelect&&!route.query.sessionId&&data.records[0])await choose(data.records[0].id)}catch(e){if(mounted&&v===listVersion)error.value=reason(e)}finally{if(v===listVersion)listing.value=false}}
async function choose(id:number){if(working.value)return;await router.replace({path:'/ai/chat',query:{sessionId:String(id)}})}
async function latest(v=viewVersion){if(!selected.value)return;const data=await historyPage(selected.value.id);if(!mounted||v!==viewVersion)return;messages.value=data.records;hasMore.value=data.hasMore;beforeId.value=data.nextBeforeId??undefined;await nextTick();if(feed.value)feed.value.scrollTop=feed.value.scrollHeight}
async function openFromRoute(){const v=++viewVersion;selected.value=null;messages.value=[];hasMore.value=false;beforeId.value=undefined;error.value='';query.value='';pending.value=null;sending.value=false;olderLoading.value=false;renameVisible.value=false;const value=route.query.sessionId;if(value===undefined){loading.value=false;return}loading.value=true;try{const id=Number(value);if(typeof value!=='string'||!Number.isSafeInteger(id)||id<1)throw Error('资料会话编号不正确');const session=await sessionDetail(id);if(!mounted||v!==viewVersion)return;selected.value=session;await latest(v)}catch(e){if(mounted&&v===viewVersion){selected.value=null;messages.value=[];error.value=reason(e)}}finally{if(v===viewVersion)loading.value=false}}
watch(()=>route.query.sessionId,openFromRoute,{immediate:true})
onMounted(()=>void list(true))
async function create(){if(working.value)return;mutating.value=true;error.value='';try{const session=await createSession();if(!mounted)return;current.value=1;await list();await router.replace({path:'/ai/chat',query:{sessionId:String(session.id)}})}catch(e){if(mounted)error.value=reason(e)}finally{if(mounted)mutating.value=false}}
async function refresh(){if(working.value)return;const saved=pending.value,draft=query.value;await openFromRoute();if(saved&&selected.value?.id===saved.sessionId){pending.value=saved;query.value=draft}await list()}
async function older(){if(!selected.value||!hasMore.value||!beforeId.value||olderLoading.value||working.value)return;const v=viewVersion,id=selected.value.id,cursor=beforeId.value;olderLoading.value=true;const height=feed.value?.scrollHeight||0;try{const data=await historyPage(id,cursor);if(!mounted||v!==viewVersion)return;const seen=new Set(messages.value.map(m=>m.id));messages.value=[...data.records.filter(m=>!seen.has(m.id)),...messages.value];hasMore.value=data.hasMore;beforeId.value=data.nextBeforeId??undefined;await nextTick();if(feed.value)feed.value.scrollTop+=feed.value.scrollHeight-height}catch(e){if(mounted&&v===viewVersion)error.value=reason(e)}finally{if(v===viewVersion)olderLoading.value=false}}
async function search(retry=false){if(!selected.value||working.value)return;if(!retry&&pending.value)return;if(!retry&&query.value.trim().length<2){error.value='请填写至少2字的具体地点或关键字';return}if(!retry)pending.value={sessionId:selected.value.id,query:query.value.trim(),topK:topK.value,requestId:crypto.randomUUID()};const input=pending.value;if(!input)return;const v=viewVersion;sending.value=true;error.value='';try{const turn=await searchInSession(input);if(!mounted||v!==viewVersion)return;selected.value=turn.session;pending.value=null;query.value='';await latest(v);await list();if(turn.replayed)ElMessage.info('已恢复这次检索的记录，没有重复保存')}catch(e){if(mounted&&v===viewVersion){error.value=reason(e);if([400,404,409].includes((e as {code?:number}).code||0))pending.value=null}}finally{if(v===viewVersion)sending.value=false}}
function startRename(){if(!selected.value||working.value)return;renameTarget.value={...selected.value};renameTitle.value=selected.value.title;renameError.value='';renameVisible.value=true}
async function rename(){if(!renameTarget.value||working.value)return;if(!renameTitle.value.trim()){renameError.value='请填写会话标题';return}const v=viewVersion;mutating.value=true;renameError.value='';try{const changed=await renameSession(renameTarget.value,renameTitle.value);if(!mounted||v!==viewVersion)return;selected.value=changed;renameVisible.value=false;await list();ElMessage.success('会话已重命名')}catch(e){if(mounted&&v===viewVersion)renameError.value=(e as {code?:number}).code===409?'会话已变化，标题输入已保留。请复制需要的内容，关闭后刷新会话再修改。':reason(e)}finally{if(mounted)mutating.value=false}}
async function remove(){if(!selected.value||working.value)return;const target={...selected.value};try{await ElMessageBox.confirm(`删除“${target.title}”及其检索记录？`,'删除资料会话',{type:'warning'});mutating.value=true;await deleteSession(target);if(!mounted)return;if(selected.value?.id===target.id)await router.replace({path:'/ai/chat'});await list();ElMessage.success('会话及检索记录已删除')}catch(e){if(mounted&&e instanceof Error)error.value=reason(e)}finally{if(mounted)mutating.value=false}}
</script>

<template><main class="knowledge-sessions"><div class="page-heading"><div><h1>资料检索会话</h1><p>保存每次资料检索，回看原文与来源。每个问题独立按关键字检索，当前不生成模型回答。</p></div><router-link to="/knowledge">快速检索资料</router-link></div>
<el-alert v-if="error" :title="error" type="error" :closable="false"/>
<div class="session-grid"><aside class="session-sidebar" v-loading="listing"><el-button type="primary" :disabled="working" @click="create">新建资料会话</el-button><el-input v-model="keyword" aria-label="会话标题筛选" placeholder="按标题查找会话" maxlength="100" clearable @keyup.enter="current=1;list()"/><el-button :disabled="working" @click="current=1;list()">查询会话</el-button><div class="session-list"><button v-for="s in sessions" :key="s.id" :data-testid="`session-${s.id}`" class="session-choice" :class="{active:selected?.id===s.id}" :disabled="working" @click="choose(s.id)"><strong>{{s.title}}</strong><span>{{Math.floor(s.messageCount/2)}}次检索 · {{new Date(s.updateTime).toLocaleString('zh-CN')}}</span></button><p v-if="!sessions.length" class="hint">暂无资料会话</p></div><Pagination :total="total" :current="current" :size="20" @change="p=>{current=p;list()}"/></aside>
<section class="session-main" v-loading="loading"><template v-if="selected"><header class="session-heading"><div><h2 data-testid="selected-session-title">{{selected.title}}</h2><p class="hint">已保存{{Math.floor(selected.messageCount/2)}}次检索，最多200次。历史引用在读取时检查是否仍公开。</p></div><div class="actions"><el-button :disabled="working" @click="refresh">刷新会话</el-button><el-button :disabled="working" @click="startRename">重命名</el-button><el-button type="danger" plain :disabled="working" @click="remove">删除会话</el-button></div></header>
<div ref="feed" class="messages" aria-label="会话历史" tabindex="0"><el-button v-if="hasMore" :loading="olderLoading" :disabled="working" @click="older">加载更早记录</el-button><p v-if="!messages.length" class="hint">还没有检索记录。可以从具体地点开始。</p><article v-for="m in messages" :key="m.id" class="history-message" :class="m.role==='user'?'question':'result'" :data-testid="`message-${m.id}`"><h3>{{m.role==='user'?'检索问题':'原文检索结果'}} <time>{{new Date(m.createTime).toLocaleString('zh-CN')}}</time></h3><pre v-if="m.role==='user'">{{m.content}}</pre><template v-else><p>{{m.content}}</p><template v-if="m.result"><el-alert v-if="m.result.unavailableReferenceCount" :title="m.result.message" type="warning" :closable="false"/><p v-else class="hint">{{m.result.message}}</p><article v-for="r in m.result.references" :key="r.chunkId" class="reference" data-testid="history-reference"><h4>{{r.title}}</h4><pre>{{r.excerpt}}</pre><div class="source-links"><router-link :to="r.documentPath">查看完整资料</router-link><router-link v-if="r.sourcePath" :to="r.sourcePath">查看关联{{r.sourcePath.startsWith('/route/')?'路线':'目的地'}}</router-link></div></article></template></template></article></div>
<div class="query-area"><p class="hint">资料可能过时，请核对完整来源。追问请写出明确地点，系统不会推测“那里”等指代。</p><div class="suggestions"><el-button v-for="q in ['香格里拉十月','洱海骑行','滇池']" :key="q" size="small" :disabled="working||!!pending" @click="query=q">{{q}}</el-button></div><el-input v-model="query" aria-label="会话检索问题" type="textarea" :rows="2" maxlength="200" :disabled="working" placeholder="例如：香格里拉十月要注意什么"/><div class="query-actions"><el-select v-model="topK" aria-label="会话片段数" :disabled="working||!!pending"><el-option v-for="n in 5" :key="n" :label="`${n}个片段`" :value="n"/></el-select><el-button type="primary" :loading="sending" :disabled="working||!!pending" @click="search()">检索并保存</el-button><template v-if="pending&&!sending"><el-button :disabled="working" @click="search(true)">重试这次检索</el-button><el-button :disabled="working" @click="pending=null">改为新的检索</el-button></template></div><p v-if="pending&&!sending" class="hint">上次请求尚未确认。重试会恢复同一次检索，避免重复保存。</p></div></template><el-empty v-else description="新建或选择一个资料会话，开始保存检索记录"/></section></div>
<el-dialog v-model="renameVisible" title="重命名资料会话" width="min(500px, calc(100vw - 24px))" :close-on-click-modal="!mutating" :show-close="!mutating"><el-alert v-if="renameError" :title="renameError" type="error" :closable="false"/><el-input v-model="renameTitle" aria-label="新的会话标题" maxlength="100" :disabled="mutating"/><template #footer><el-button :disabled="mutating" @click="renameVisible=false">取消</el-button><el-button type="primary" :loading="mutating" @click="rename">保存标题</el-button></template></el-dialog>
</main></template>

<style scoped>
.knowledge-sessions{max-width:1280px;margin:auto;padding:28px 20px 60px;overflow-wrap:anywhere}.page-heading,.session-heading{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.page-heading h1{margin:0}.page-heading p,.hint{color:var(--trip-muted);line-height:1.8}.page-heading>a{white-space:nowrap}.session-grid{display:grid;grid-template-columns:270px minmax(0,1fr);gap:20px;margin-top:20px}.session-sidebar,.session-main{padding:20px;background:white;border:1px solid var(--trip-border);border-radius:14px;min-width:0}.session-sidebar>.el-input{margin:16px 0 10px}.session-list{max-height:560px;overflow:auto;margin-top:12px}.session-choice{display:block;text-align:left;width:100%;border:0;background:var(--trip-canvas);border-radius:8px;padding:12px;margin:8px 0;cursor:pointer;overflow-wrap:anywhere}.session-choice.active{background:#e7f0ff}.session-choice strong,.session-choice span{display:block}.session-choice span{font-size:12px;color:var(--trip-muted);margin-top:6px}.session-heading h2{margin:0;font-size:20px}.session-heading{flex-wrap:wrap}.actions,.query-actions,.source-links,.suggestions{display:flex;gap:10px;flex-wrap:wrap}.actions>.el-button,.query-actions>.el-button,.suggestions>.el-button{margin-left:0}.messages{max-height:650px;overflow:auto;margin:20px 0;scrollbar-gutter:stable}.history-message{padding:16px;background:var(--trip-canvas);border-radius:10px;margin:14px 0}.question{background:var(--trip-tint)}.history-message h3{font-size:15px;margin-top:0}.history-message time{display:block;font-size:12px;color:var(--trip-muted);font-weight:400;margin-top:6px}.reference{padding:14px;margin:12px 0;background:white;border:1px solid var(--trip-border);border-radius:10px}.reference h4{margin:0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;line-height:1.8}.query-area{border-top:1px solid var(--trip-border);padding-top:10px}.suggestions{margin-bottom:12px}.query-actions{margin-top:12px}.query-actions>.el-select{width:140px}@media(max-width:760px){.knowledge-sessions{padding:22px 10px}.page-heading{flex-wrap:wrap}.session-grid{grid-template-columns:minmax(0,1fr)}.session-sidebar,.session-main{padding:14px}.session-list{max-height:220px}.messages{max-height:560px}.reference{padding:10px}}
</style>
