<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { preferenceApi, savePreferenceApi, type UserPreference } from '@/api/modules/user'
import { travelTags as tags } from '@/utils/travelTags'
const form=reactive<UserPreference>({preferenceTags:[],avoidTags:[],budgetMin:0,budgetMax:0,preferredDays:null,companions:'',pace:''}),loading=ref(false),saving=ref(false)
const failed=ref(false)
async function load(){loading.value=true;failed.value=false;try{Object.assign(form,await preferenceApi())}catch{failed.value=true}finally{loading.value=false}}
async function save(){if(saving.value||loading.value||failed.value)return;const input={...form,budgetMin:form.budgetMin??0,budgetMax:form.budgetMax??0,preferredDays:form.preferredDays??null};if(input.preferenceTags.some(x=>input.avoidTags.includes(x))){ElMessage.warning('偏好标签与避雷标签不能重复');return}if((input.budgetMin||input.budgetMax)&&input.budgetMin>=input.budgetMax){ElMessage.warning('预算下限必须小于上限');return}saving.value=true;try{Object.assign(form,await savePreferenceApi(input));ElMessage.success('旅行偏好已保存')}catch{}finally{saving.value=false}}
onMounted(load)
</script>
<template><main class="preference" v-loading="loading"><h1>旅行偏好</h1><p class="hint">推荐页可用这些偏好预填未明确的条件，本次修改或清空优先。预算指路线人均参考价，均为0表示不限；同行人和节奏暂不参与筛选。</p><el-alert v-if="failed" title="偏好加载失败，请重试后再编辑" type="error" :closable="false"/><el-button :loading="loading" @click="load">刷新偏好</el-button><section class="card panel"><el-form label-position="top" :disabled="loading||failed||saving"><el-form-item label="偏好标签（最多8个）"><el-select v-model="form.preferenceTags" multiple :multiple-limit="8" filterable aria-label="偏好标签"><el-option v-for="tag in tags" :key="tag" :label="tag" :value="tag"/></el-select></el-form-item><el-form-item label="避雷标签（最多5个）"><el-select v-model="form.avoidTags" multiple :multiple-limit="5" filterable aria-label="避雷标签"><el-option v-for="tag in tags" :key="tag" :label="tag" :value="tag"/></el-select></el-form-item><div class="fields"><el-form-item label="预算下限"><el-input-number v-model="form.budgetMin" :min="0" :max="99999999.99" :precision="2" aria-label="预算下限"/></el-form-item><el-form-item label="预算上限"><el-input-number v-model="form.budgetMax" :min="0" :max="99999999.99" :precision="2" aria-label="预算上限"/></el-form-item><el-form-item label="常用天数"><el-input-number v-model="form.preferredDays" :min="1" :max="30" :precision="0" controls-position="right" aria-label="常用天数"/><el-button link @click="form.preferredDays=null">不限天数</el-button></el-form-item><el-form-item label="同行人"><el-select v-model="form.companions" aria-label="同行人"><el-option label="未设置" value=""/><el-option label="独自出行" value="single"/><el-option label="情侣" value="couple"/><el-option label="家庭" value="family"/><el-option label="团体" value="group"/></el-select></el-form-item><el-form-item label="旅行节奏"><el-select v-model="form.pace" aria-label="旅行节奏"><el-option label="未设置" value=""/><el-option label="轻松" value="relaxed"/><el-option label="正常" value="normal"/><el-option label="紧凑" value="intense"/></el-select></el-form-item></div><el-button type="primary" :loading="saving" @click="save">保存偏好</el-button><router-link to="/recommend">前往旅行推荐</router-link></el-form></section></main></template>
<style scoped>.preference{max-width:850px;margin:auto;padding:24px 16px}.panel{padding:24px;margin:20px 0}.hint{color:#64748b}.fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}@media(max-width:640px){.fields{grid-template-columns:1fr}.panel{padding:16px}}</style>
