<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { preferenceApi, savePreferenceApi, type UserPreference } from '@/api/modules/user'
const tags=['自然风光','历史文化','美食','亲子','摄影','探险','海滨','都市','购物','温泉','滑雪','徒步','自驾','民俗','宗教','康养']
const form=reactive<UserPreference>({preferenceTags:[],avoidTags:[],budgetMin:0,budgetMax:0,preferredDays:null,companions:'',pace:''}),loading=ref(false),saving=ref(false)
async function load(){loading.value=true;try{Object.assign(form,await preferenceApi())}finally{loading.value=false}}
async function save(){if(form.preferenceTags.some(x=>form.avoidTags.includes(x))){ElMessage.warning('偏好标签与避雷标签不能重复');return}if((form.budgetMin||form.budgetMax)&&form.budgetMin>=form.budgetMax){ElMessage.warning('预算下限必须小于上限');return}saving.value=true;try{Object.assign(form,await savePreferenceApi({...form}));ElMessage.success('旅行偏好已保存')}finally{saving.value=false}}
onMounted(load)
</script>
<template><main class="preference" v-loading="loading"><h1>旅行偏好</h1><p class="hint">偏好会帮助基础推荐排序，也可在每次推荐前手动修改需求。</p><section class="card panel"><el-form label-position="top"><el-form-item label="偏好标签（最多8个）"><el-select v-model="form.preferenceTags" multiple filterable aria-label="偏好标签"><el-option v-for="tag in tags" :key="tag" :label="tag" :value="tag"/></el-select></el-form-item><el-form-item label="避雷标签（最多5个）"><el-select v-model="form.avoidTags" multiple filterable aria-label="避雷标签"><el-option v-for="tag in tags" :key="tag" :label="tag" :value="tag"/></el-select></el-form-item><div class="fields"><el-form-item label="预算下限"><el-input-number v-model="form.budgetMin" :min="0" :precision="2" aria-label="预算下限"/></el-form-item><el-form-item label="预算上限"><el-input-number v-model="form.budgetMax" :min="0" :precision="2" aria-label="预算上限"/></el-form-item><el-form-item label="常用天数"><el-input-number v-model="form.preferredDays" :min="1" :max="30" :precision="0" controls-position="right" aria-label="常用天数"/></el-form-item><el-form-item label="同行人"><el-select v-model="form.companions" aria-label="同行人"><el-option label="未设置" value=""/><el-option label="独自出行" value="single"/><el-option label="情侣" value="couple"/><el-option label="家庭" value="family"/><el-option label="团体" value="group"/></el-select></el-form-item><el-form-item label="旅行节奏"><el-select v-model="form.pace" aria-label="旅行节奏"><el-option label="未设置" value=""/><el-option label="轻松" value="relaxed"/><el-option label="正常" value="normal"/><el-option label="紧凑" value="intense"/></el-select></el-form-item></div><el-button type="primary" :loading="saving" @click="save">保存偏好</el-button></el-form></section></main></template>
<style scoped>.preference{max-width:850px;margin:auto;padding:24px 16px}.panel{padding:24px;margin:20px 0}.hint{color:#64748b}.fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}@media(max-width:640px){.fields{grid-template-columns:1fr}.panel{padding:16px}}</style>
