<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { profileApi, updateProfileApi, changePasswordApi, uploadImageApi, type UserProfile } from '@/api/modules/user'
import { useUserStore } from '@/store/user'
const store=useUserStore(), loading=ref(false),saving=ref(false),passwordSaving=ref(false),uploading=ref(false)
const profile=reactive({nickname:'',avatar:'',phone:'',email:'',city:''}), password=reactive({oldPassword:'',newPassword:'',confirm:''})
async function load(){loading.value=true;try{const data:UserProfile=await profileApi();Object.assign(profile,{nickname:data.nickname||'',avatar:data.avatar||'',phone:data.phone||'',email:data.email||'',city:data.city||''});store.updateProfile(data)}finally{loading.value=false}}
async function save(){if(!profile.nickname.trim()){ElMessage.warning('昵称不能为空');return} saving.value=true;try{const data=await updateProfileApi({...profile,nickname:profile.nickname.trim()});store.updateProfile(data);ElMessage.success('资料已保存')}finally{saving.value=false}}
async function changePassword(){if(password.newPassword!==password.confirm){ElMessage.warning('两次新密码不一致');return}passwordSaving.value=true;try{await changePasswordApi({oldPassword:password.oldPassword,newPassword:password.newPassword});ElMessage.success('密码已修改，请重新登录');store.resetSession();location.href='/login'}finally{passwordSaving.value=false}}
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>5*1024*1024){ElMessage.warning('请选择5MB以内PNG/JPEG图片');return}uploading.value=true;try{profile.avatar=(await uploadImageApi(file)).url;ElMessage.success('头像上传成功')}finally{uploading.value=false;(event.target as HTMLInputElement).value=''}}
onMounted(load)
</script>
<template><main class="profile" v-loading="loading"><h1>个人资料</h1><section class="card panel"><h2>基本资料</h2><el-form label-position="top"><el-form-item label="登录名"><el-input :model-value="store.userInfo?.username" disabled/></el-form-item><el-form-item label="昵称"><el-input v-model="profile.nickname" maxlength="50" aria-label="昵称"/></el-form-item><el-form-item label="头像"><div class="avatar-edit"><el-avatar :size="72" :src="profile.avatar"/><input type="file" accept="image/png,image/jpeg" :disabled="uploading" aria-label="选择头像" @change="upload"/></div></el-form-item><el-form-item label="手机号"><el-input v-model="profile.phone" maxlength="20" aria-label="手机号"/></el-form-item><el-form-item label="邮箱"><el-input v-model="profile.email" maxlength="100" aria-label="邮箱"/></el-form-item><el-form-item label="所在城市"><el-input v-model="profile.city" maxlength="50" aria-label="所在城市"/></el-form-item><el-button type="primary" :loading="saving" @click="save">保存资料</el-button></el-form></section><section class="card panel"><h2>修改密码</h2><el-form label-position="top"><el-form-item label="原密码"><el-input v-model="password.oldPassword" type="password" show-password aria-label="原密码"/></el-form-item><el-form-item label="新密码"><el-input v-model="password.newPassword" type="password" show-password aria-label="新密码" placeholder="8—20位，含字母和数字"/></el-form-item><el-form-item label="确认新密码"><el-input v-model="password.confirm" type="password" show-password aria-label="确认新密码"/></el-form-item><el-button type="warning" :loading="passwordSaving" @click="changePassword">修改密码</el-button></el-form></section></main></template>
<style scoped>.profile{max-width:760px;margin:auto;padding:24px 16px}.panel{padding:24px;margin:20px 0}.avatar-edit{display:flex;align-items:center;gap:16px}.avatar-edit input{max-width:260px}@media(max-width:640px){.panel{padding:16px}}</style>
