<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { bannerPage, saveBanner, deleteBanner, type Banner, type BannerInput } from '@/api/modules/catalog'
import Pagination from '@/components/common/Pagination.vue'
import AdminImageField from '@/components/common/AdminImageField.vue'
const rows=ref<Banner[]>([]),current=ref(1),total=ref(0),loading=ref(false),busy=ref(false),visible=ref(false),editing=ref<number>()
const fresh=():BannerInput=>({title:'',imageUrl:'',linkType:'NONE',linkValue:'',sortNo:0,status:0,startTime:null,endTime:null})
const form=ref(fresh());let version=0
async function load(){const v=++version;loading.value=true;try{const p=await bannerPage(current.value);if(v!==version)return;rows.value=p.records;total.value=p.total;if(!p.records.length&&current.value>1){current.value=Math.max(1,p.pages);await load()}}catch{}finally{if(v===version)loading.value=false}}
function edit(row?:Banner){editing.value=row?.id;form.value=row?{...row}:fresh();visible.value=true}
async function save(){if(busy.value)return;if(!form.value.title.trim()||!form.value.imageUrl.trim()||(form.value.linkType!=='NONE'&&!form.value.linkValue.trim())){ElMessage.warning('请填写标题、图片和跳转目标');return}busy.value=true;try{await saveBanner({...form.value,linkValue:form.value.linkType==='NONE'?'':form.value.linkValue,startTime:form.value.startTime||null,endTime:form.value.endTime||null},editing.value);visible.value=false;await load();ElMessage.success('轮播已保存')}catch{}finally{busy.value=false}}
async function act(row:Banner,remove=false){if(busy.value)return;try{await ElMessageBox.confirm(`确认${remove?'删除':row.status?'停用':'启用'}“${row.title}”？`,'更新轮播',{type:'warning'});busy.value=true;if(remove)await deleteBanner(row.id);else await saveBanner({...row,status:row.status?0:1},row.id);await load();ElMessage.success('轮播已更新')}catch{}finally{busy.value=false}}
onMounted(load)
</script>
<template><main class="admin-page"><h1>首页轮播</h1><p class="admin-help">最多启用8张。排序越小越靠前；未到开始时间、已到结束时间或跳转内容已下架的轮播不会在首页出现。</p><section class="admin-panel" v-loading="loading"><div class="admin-tools"><el-button @click="load">刷新</el-button><el-button type="primary" :disabled="busy" @click="edit()">新增轮播</el-button></div><el-table :data="rows" empty-text="暂无轮播"><el-table-column label="图片" width="100"><template #default="s"><img class="admin-cover" :src="s.row.imageUrl" :alt="s.row.title"/></template></el-table-column><el-table-column prop="title" label="标题" min-width="160"/><el-table-column prop="sortNo" label="排序" width="75"/><el-table-column label="跳转" min-width="150"><template #default="s">{{s.row.linkType}} {{s.row.linkValue}}</template></el-table-column><el-table-column label="状态" width="85"><template #default="s">{{s.row.status?'已启用':'已停用'}}</template></el-table-column><el-table-column label="有效时间" min-width="210"><template #default="s">{{s.row.startTime||'立即生效'}} → {{s.row.endTime||'长期有效'}}</template></el-table-column><el-table-column label="操作" min-width="190"><template #default="s"><el-button link :disabled="busy" @click="edit(s.row)">编辑</el-button><el-button link :disabled="busy" @click="act(s.row)">{{s.row.status?'停用':'启用'}}</el-button><el-button link type="danger" :disabled="busy" @click="act(s.row,true)">删除</el-button></template></el-table-column></el-table><div class="admin-pagination"><Pagination :total="total" :current="current" :size="20" @change="p=>{current=p;load()}"/></div></section>
  <el-dialog v-model="visible" :title="editing?'编辑轮播':'新增轮播'" class="admin-dialog" width="min(780px, calc(100vw - 24px))" :close-on-click-modal="!busy" :close-on-press-escape="!busy" :show-close="!busy"><el-form class="admin-form" label-position="top" :disabled="busy"><el-form-item label="标题（必填）" class="wide"><el-input v-model="form.title" aria-label="轮播标题" maxlength="100"/></el-form-item><el-form-item label="图片（必填）" class="wide"><AdminImageField v-model="form.imageUrl" label="轮播图片地址"/></el-form-item><el-form-item label="跳转类型"><el-select v-model="form.linkType" aria-label="轮播跳转类型" @change="form.linkValue='' "><el-option label="不跳转" value="NONE"/><el-option label="路线" value="ROUTE"/><el-option label="目的地" value="DESTINATION"/><el-option label="外部网页" value="URL"/></el-select></el-form-item><el-form-item label="目标ID / HTTP(S)地址"><el-input v-model="form.linkValue" aria-label="轮播跳转目标" :disabled="form.linkType==='NONE'" maxlength="255" placeholder="路线或目的地填写ID，网页填写完整地址"/></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sortNo" aria-label="轮播排序" :min="0" :max="10000"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" aria-label="轮播保存状态"><el-option label="已停用" :value="0"/><el-option label="已启用" :value="1"/></el-select></el-form-item><el-form-item label="开始时间（可不填）"><el-date-picker v-model="form.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" aria-label="轮播开始时间"/></el-form-item><el-form-item label="结束时间（可不填）"><el-date-picker v-model="form.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" aria-label="轮播结束时间"/></el-form-item></el-form><template #footer><el-button :disabled="busy" @click="visible=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存轮播</el-button></template></el-dialog></main></template>
