<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { catalogDestinations, saveDestination, deleteDestination, destinationStatus, catalogAttractions, saveAttraction, deleteAttraction, type DestinationInput, type AttractionInput } from '@/api/modules/catalog'
import Pagination from '@/components/common/Pagination.vue'
import AdminImageField from '@/components/common/AdminImageField.vue'
const rows=ref<DestinationVO[]>([]),total=ref(0),current=ref(1),keyword=ref(''),status=ref(-1),loading=ref(false),busy=ref(false)
const visible=ref(false),editing=ref<number>(),tags=ref('')
const fresh=():DestinationInput=>({name:'',province:'',city:'',longitude:120,latitude:30,coverImg:'',intro:'',tags:[],bestSeason:'',avgCost:0,status:0})
const form=ref(fresh())
const parent=ref<DestinationVO>(),attractions=ref<AttractionVO[]>([]),drawer=ref(false),attractionVisible=ref(false),attractionId=ref<number>(),attractionTags=ref('')
const freshAttraction=():AttractionInput=>({name:'',coverImg:'',intro:'',address:'',longitude:120,latitude:30,ticketPrice:0,openTime:'',durationMin:60,tags:[],status:1})
const attractionForm=ref(freshAttraction())
let version=0
async function load(){const v=++version;loading.value=true;try{const p=await catalogDestinations({current:current.value,keyword:keyword.value.trim()||undefined,status:status.value<0?undefined:status.value});if(v!==version)return;rows.value=p.records;total.value=p.total;if(!p.records.length&&current.value>1){current.value=Math.max(1,p.pages);await load()}}catch{}finally{if(v===version)loading.value=false}}
function search(){current.value=1;void load()}
function edit(row?:DestinationVO){editing.value=row?.id;form.value=row?{...fresh(),...row,tags:row.tags||[]} as DestinationInput:fresh();tags.value=form.value.tags.join('，');visible.value=true}
const split=(text:string)=>text.split(/[,，]/).map(s=>s.trim()).filter(Boolean)
async function save(){if(busy.value)return;if(!form.value.name.trim()||!form.value.province.trim()||!form.value.coverImg.trim()){ElMessage.warning('请填写名称、省份和封面图片');return}busy.value=true;try{await saveDestination({...form.value,tags:split(tags.value)},editing.value);visible.value=false;ElMessage.success('目的地已保存');await load()}catch{}finally{busy.value=false}}
async function act(row:DestinationVO,remove=false){if(busy.value)return;try{await ElMessageBox.confirm(remove?'删除目的地会同时删除其景点；有关联路线时不能删除。':`确认${row.status===1?'下架':'上架'}“${row.name}”？`,remove?'删除目的地':'更改上架状态',{type:'warning'});busy.value=true;if(remove)await deleteDestination(row.id);else await destinationStatus(row.id,row.status===1?0:1);ElMessage.success('目的地已更新');await load()}catch{}finally{busy.value=false}}
async function loadAttractions(){if(!parent.value)return;try{attractions.value=await catalogAttractions(parent.value.id)}catch{}}
async function openAttractions(row:DestinationVO){parent.value=row;attractions.value=[];drawer.value=true;await loadAttractions()}
function editAttraction(row?:AttractionVO){attractionId.value=row?.id;attractionForm.value=row?{...freshAttraction(),...row,tags:row.tags||[]} as AttractionInput:{...freshAttraction(),longitude:parent.value?.longitude||120,latitude:parent.value?.latitude||30};attractionTags.value=attractionForm.value.tags.join('，');attractionVisible.value=true}
async function saveSpot(){if(!parent.value||busy.value)return;if(!attractionForm.value.name.trim()){ElMessage.warning('请填写景点名称');return}busy.value=true;try{await saveAttraction(parent.value.id,{...attractionForm.value,tags:split(attractionTags.value)},attractionId.value);attractionVisible.value=false;ElMessage.success('景点已保存');await loadAttractions()}catch{}finally{busy.value=false}}
async function removeSpot(row:AttractionVO){if(busy.value)return;try{await ElMessageBox.confirm(`确认删除“${row.name}”？已有行程中的文字快照会保留。`,'删除景点',{type:'warning'});busy.value=true;await deleteAttraction(row.id);await loadAttractions();ElMessage.success('景点已删除')}catch{}finally{busy.value=false}}
onMounted(load)
</script>
<template>
  <main class="admin-page"><h1>目的地与景点</h1><p class="admin-help">先维护目的地和景点，再编写路线。下架目的地后，关联内容将从前台隐藏。</p>
    <section class="admin-panel" v-loading="loading"><div class="admin-tools"><el-input v-model="keyword" aria-label="搜索目的地" placeholder="目的地名称" clearable @keyup.enter="search"/><el-select v-model="status" aria-label="目的地状态" @change="search"><el-option label="全部状态" :value="-1"/><el-option label="已上架" :value="1"/><el-option label="已下架" :value="0"/></el-select><el-button @click="search">查询</el-button><el-button @click="load">刷新</el-button><el-button type="primary" :disabled="busy" @click="edit()">新增目的地</el-button></div>
      <el-table :data="rows" empty-text="暂无目的地"><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="name" label="名称" min-width="150"/><el-table-column prop="province" label="省份" width="100"/><el-table-column prop="city" label="城市" width="100"/><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.status===1?'success':'info'">{{s.row.status===1?'已上架':'已下架'}}</el-tag></template></el-table-column><el-table-column label="操作" min-width="260"><template #default="s"><div class="admin-row-actions"><el-button link @click="edit(s.row)">编辑</el-button><el-button link @click="openAttractions(s.row)">景点</el-button><el-button link :disabled="busy" @click="act(s.row)">{{s.row.status===1?'下架':'上架'}}</el-button><el-button link type="danger" :disabled="busy" @click="act(s.row,true)">删除</el-button></div></template></el-table-column></el-table>
      <div class="admin-pagination"><Pagination :total="total" :current="current" :size="20" @change="p=>{current=p;load()}"/></div></section>
    <el-dialog v-model="visible" :title="editing?'编辑目的地':'新增目的地'" class="admin-dialog" width="min(780px, calc(100vw - 24px))" :close-on-click-modal="!busy" :close-on-press-escape="!busy" :show-close="!busy">
      <el-form class="admin-form" label-position="top" :disabled="busy">
        <el-form-item label="名称（必填）"><el-input v-model="form.name" aria-label="目的地名称" maxlength="100"/></el-form-item><el-form-item label="省份（必填）"><el-input v-model="form.province" aria-label="目的地省份" maxlength="50"/></el-form-item><el-form-item label="城市"><el-input v-model="form.city" aria-label="目的地城市" maxlength="50"/></el-form-item><el-form-item label="最佳季节"><el-input v-model="form.bestSeason" aria-label="最佳季节" maxlength="50"/></el-form-item>
        <el-form-item label="经度（73—136）"><el-input-number v-model="form.longitude" aria-label="目的地经度" :min="73" :max="136" :precision="6"/></el-form-item><el-form-item label="纬度（3—54）"><el-input-number v-model="form.latitude" aria-label="目的地纬度" :min="3" :max="54" :precision="6"/></el-form-item>
        <el-form-item label="参考人均费用"><el-input-number v-model="form.avgCost" aria-label="目的地费用" :min="0" :max="99999999.99" :precision="2"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" aria-label="目的地保存状态"><el-option label="已下架" :value="0"/><el-option label="已上架" :value="1"/></el-select></el-form-item>
        <el-form-item label="封面图片（必填）" class="wide"><AdminImageField v-model="form.coverImg"/></el-form-item><el-form-item label="标签（最多5个，逗号分隔）" class="wide"><el-input v-model="tags" aria-label="目的地标签"/></el-form-item><el-form-item label="简介" class="wide"><el-input v-model="form.intro" aria-label="目的地简介" type="textarea" :rows="4" maxlength="10000"/></el-form-item>
      </el-form><template #footer><el-button :disabled="busy" @click="visible=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存目的地</el-button></template></el-dialog>
    <el-drawer v-model="drawer" :title="`${parent?.name||''} · 景点管理`" size="min(900px, 100vw)"><el-button type="primary" :disabled="busy" @click="editAttraction()">新增景点</el-button><p class="admin-note">景点所属目的地不可修改。下架景点不会删除已有行程的文字快照。</p><el-table :data="attractions" empty-text="暂无景点"><el-table-column prop="name" label="名称" min-width="150"/><el-table-column prop="ticketPrice" label="门票" width="100"/><el-table-column label="状态" width="90"><template #default="s">{{s.row.status===1?'已上架':'已下架'}}</template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button link @click="editAttraction(s.row)">编辑</el-button><el-button link type="danger" :disabled="busy" @click="removeSpot(s.row)">删除</el-button></template></el-table-column></el-table></el-drawer>
    <el-dialog v-model="attractionVisible" :title="attractionId?'编辑景点':'新增景点'" append-to-body class="admin-dialog" width="min(780px, calc(100vw - 24px))" :close-on-click-modal="!busy" :close-on-press-escape="!busy" :show-close="!busy">
      <el-form class="admin-form" label-position="top" :disabled="busy"><el-form-item label="名称（必填）"><el-input v-model="attractionForm.name" aria-label="景点名称" maxlength="100"/></el-form-item><el-form-item label="地址"><el-input v-model="attractionForm.address" aria-label="景点地址" maxlength="255"/></el-form-item><el-form-item label="经度"><el-input-number v-model="attractionForm.longitude" aria-label="景点经度" :min="-180" :max="180" :precision="6"/></el-form-item><el-form-item label="纬度"><el-input-number v-model="attractionForm.latitude" aria-label="景点纬度" :min="-90" :max="90" :precision="6"/></el-form-item><el-form-item label="门票费用"><el-input-number v-model="attractionForm.ticketPrice" aria-label="景点门票" :min="0" :max="99999999.99" :precision="2"/></el-form-item><el-form-item label="游玩时长（分钟）"><el-input-number v-model="attractionForm.durationMin" aria-label="景点时长" :min="0" :max="1440"/></el-form-item><el-form-item label="开放时间"><el-input v-model="attractionForm.openTime" aria-label="景点开放时间" maxlength="100"/></el-form-item><el-form-item label="状态"><el-select v-model="attractionForm.status" aria-label="景点状态"><el-option label="已上架" :value="1"/><el-option label="已下架" :value="0"/></el-select></el-form-item><el-form-item label="封面图片" class="wide"><AdminImageField v-model="attractionForm.coverImg" label="景点封面地址"/></el-form-item><el-form-item label="标签（最多5个，逗号分隔）" class="wide"><el-input v-model="attractionTags" aria-label="景点标签"/></el-form-item><el-form-item label="简介" class="wide"><el-input v-model="attractionForm.intro" aria-label="景点简介" type="textarea" :rows="4" maxlength="10000"/></el-form-item></el-form>
      <template #footer><el-button :disabled="busy" @click="attractionVisible=false">取消</el-button><el-button type="primary" :loading="busy" @click="saveSpot">保存景点</el-button></template>
    </el-dialog>
  </main>
</template>
