<script setup lang="ts">
import {onBeforeUnmount,onMounted,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import Pagination from '@/components/common/Pagination.vue'
import KnowledgeMaintenance from './KnowledgeMaintenance.vue'
import {knowledgePage,knowledgeDetail,saveKnowledge,setKnowledgeState,deleteKnowledge,rebuildKnowledge,uploadKnowledge,type KnowledgeDoc,type KnowledgeInput} from '@/api/modules/knowledge'
import KnowledgeSourcePicker from './KnowledgeSourcePicker.vue'
import KnowledgeSourceDialog from './KnowledgeSourceDialog.vue'
const rows=ref<KnowledgeDoc[]>([]),current=ref(1),total=ref(0),loading=ref(false),busy=ref(false),visible=ref(false),editing=ref<number>(),keyword=ref(''),status=ref<number>(),error=ref('')
const selected=ref<KnowledgeDoc[]>([]),indexState=ref<KnowledgeDoc['indexState']>(),sourceState=ref<KnowledgeDoc['sourceState']>(),refreshKey=ref(0),table=ref<{clearSelection:()=>void}>()
function selectionChanged(value:KnowledgeDoc[]){selected.value=value}
const fresh=():KnowledgeInput=>({title:'',docType:'GUIDE',sourceId:null,content:'',status:0})
const form=ref(fresh()),importing=ref(false),file=ref<File|null>(null),sourceDialog=ref<InstanceType<typeof KnowledgeSourceDialog>>()
let version=0,mounted=true
onBeforeUnmount(()=>{mounted=false;version++})
async function load(){const v=++version;loading.value=true;selected.value=[];table.value?.clearSelection();try{const p=await knowledgePage({current:current.value,keyword:keyword.value.trim()||undefined,status:status.value,indexState:indexState.value,sourceState:sourceState.value});if(!mounted||v!==version)return;rows.value=p.records;total.value=p.total;refreshKey.value++;if(!p.records.length&&current.value>1){current.value=Math.max(1,p.pages);await load()}}catch{}finally{if(v===version)loading.value=false}}
async function edit(row?:KnowledgeDoc,upload=false){if(busy.value)return;busy.value=true;error.value='';try{const doc=row?await knowledgeDetail(row.id):null;if(!mounted)return;editing.value=doc?.id;importing.value=upload;file.value=null;form.value=doc?{title:doc.title,docType:doc.docType,sourceId:doc.sourceId,content:doc.content||'',status:doc.status,expectedRevision:doc.revision}:fresh();visible.value=true}catch{}finally{busy.value=false}}
function picked(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]||null}
async function save(){if(busy.value)return;if(!form.value.title.trim()||(!importing.value&&!form.value.content.trim())||(form.value.docType!=='GUIDE'&&!form.value.sourceId)){ElMessage.warning('请填写标题、正文及关联来源');return}if(importing.value&&(!file.value||!(/\.(txt|md)$/i).test(file.value.name)||file.value.size>262144)){ElMessage.warning('请选择256KiB以内的TXT/MD文件');return}busy.value=true;error.value='';try{const input={...form.value,sourceId:form.value.docType==='GUIDE'?null:form.value.sourceId};if(importing.value)await uploadKnowledge(input,file.value!);else await saveKnowledge(input,editing.value);visible.value=false;await load();ElMessage.success('资料已保存并完成本地分片')}catch(e){error.value=(e as {code?:number}).code===409?'资料版本已变化，输入已保留。请复制所需内容，关闭并刷新列表后重新编辑。':(e instanceof Error?e.message:'保存失败')}finally{busy.value=false}}
async function act(row:KnowledgeDoc,action:'status'|'delete'|'rebuild'){if(busy.value)return;try{if(action==='delete')await ElMessageBox.confirm(`确认删除“${row.title}”？删除后用户无法再查看。`,'删除资料',{type:'warning'});busy.value=true;if(action==='delete')await deleteKnowledge(row);else if(action==='rebuild')await rebuildKnowledge(row);else await setKnowledgeState(row,row.status?0:1);await load();ElMessage.success('资料已更新')}catch{}finally{busy.value=false}}
function indexText(d:KnowledgeDoc){const reasons:Record<string,string>={NOT_BUILT:'待构建',STALE_REVISION:'版本过期',MISSING_CHUNKS:'分片缺失',COUNT_MISMATCH:'分片计数不一致',CHUNK_REVISION_MISMATCH:'分片版本不一致'};return d.indexState==='READY'?'本地索引就绪':reasons[d.indexIssue||'']||'待修复'}
onMounted(load)
</script>
<template><main class="admin-page"><h1>知识资料</h1><p class="admin-help">维护旅行资料，用户可检索原文片段并查看来源。保存时完成本地分片；启用后公开，停用或删除立即隐藏。尚未接入语义向量或模型回答。</p><KnowledgeMaintenance v-model:busy="busy" :selected="selected" :refresh-key="refreshKey" @repaired="load"/><section class="admin-panel" v-loading="loading"><div class="admin-tools"><el-input v-model="keyword" aria-label="资料标题筛选" placeholder="按标题筛选" maxlength="100" clearable @keyup.enter="current=1;load()"/><el-select v-model="status" aria-label="资料状态筛选" placeholder="全部状态" clearable><el-option label="启用" :value="1"/><el-option label="停用" :value="0"/></el-select><el-select v-model="indexState" aria-label="资料索引筛选" placeholder="全部索引" clearable><el-option label="索引就绪" value="READY"/><el-option label="待修复索引" value="NEEDS_REBUILD"/></el-select><el-select v-model="sourceState" aria-label="资料来源筛选" placeholder="全部来源" clearable><el-option label="来源可用" value="AVAILABLE"/><el-option label="来源未公开" value="UNAVAILABLE"/><el-option label="待关联来源" value="UNLINKED"/></el-select><el-button :disabled="busy" @click="current=1;load()">查询</el-button><el-button type="primary" :disabled="busy" @click="edit()">新增资料</el-button><el-button :disabled="busy" @click="edit(undefined,true)">导入TXT/MD</el-button></div><el-table ref="table" :data="rows" row-key="id" empty-text="暂无资料" @selection-change="selectionChanged"><el-table-column type="selection" width="48" :selectable="()=>!busy"/><el-table-column prop="title" label="标题" min-width="190"/><el-table-column label="类型/来源" width="140"><template #default="s">{{s.row.docType==='GUIDE'?'独立攻略':s.row.docType==='ROUTE'?'路线':'目的地'}} · {{s.row.sourceType==='FILE'?'文件':'手动'}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s">{{s.row.status?'启用':'停用'}}<span v-if="s.row.sourceState==='UNLINKED'"> / 待关联来源</span><span v-else-if="!s.row.sourceAvailable"> / 来源未公开</span></template></el-table-column><el-table-column label="本地索引" min-width="155"><template #default="s">{{indexText(s.row)}} · {{s.row.actualChunkCount}}/{{s.row.chunkCount}}片</template></el-table-column><el-table-column prop="revision" label="版本" width="70"/><el-table-column label="操作" min-width="235"><template #default="s"><el-button link :disabled="busy" @click="edit(s.row)">编辑</el-button><el-button link :disabled="busy" @click="sourceDialog?.open(s.row)">调整来源</el-button><el-button link :disabled="busy" @click="act(s.row,'status')">{{s.row.status?'停用':'启用'}}</el-button><el-button link :disabled="busy" @click="act(s.row,'rebuild')">重建分片</el-button><el-button link type="danger" :disabled="busy" @click="act(s.row,'delete')">删除</el-button></template></el-table-column></el-table><Pagination :total="total" :current="current" :size="20" @change="p=>{current=p;load()}"/></section>
<el-dialog v-model="visible" :title="importing?'导入资料':editing?'编辑资料':'新增资料'" width="min(860px, calc(100vw - 24px))" class="admin-dialog" :close-on-click-modal="!busy" :close-on-press-escape="!busy" :show-close="!busy"><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top" :disabled="busy"><el-form-item label="标题"><el-input v-model="form.title" aria-label="资料标题" maxlength="200"/></el-form-item><el-form-item label="资料类型"><el-select v-model="form.docType" aria-label="资料类型" @change="form.sourceId=null"><el-option label="独立攻略" value="GUIDE"/><el-option label="目的地" value="DESTINATION"/><el-option label="路线" value="ROUTE"/></el-select></el-form-item><el-form-item v-if="form.docType!=='GUIDE'" label="关联来源"><KnowledgeSourcePicker v-model="form.sourceId" :doc-type="form.docType" :status="form.status" :disabled="busy"/></el-form-item><el-form-item label="保存状态"><el-select v-model="form.status" aria-label="资料保存状态"><el-option label="停用，先检查资料" :value="0"/><el-option label="启用并公开" :value="1"/></el-select></el-form-item><el-form-item v-if="importing" label="UTF-8 TXT/MD（≤256KiB，正文≤20000字符）"><input type="file" accept=".txt,.md,text/plain,text/markdown" aria-label="资料文件" :disabled="busy" @change="picked"/></el-form-item><el-form-item v-else label="资料正文（≤20000个字符）"><el-input v-model="form.content" aria-label="资料正文" type="textarea" :rows="12" maxlength="40000"/></el-form-item><p class="admin-note">用户看到资料原文。请核实时间、费用与来源；文件只提取正文，系统不会保留上传文件或访问外部链接。</p></el-form><template #footer><el-button :disabled="busy" @click="visible=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存资料</el-button></template></el-dialog><KnowledgeSourceDialog ref="sourceDialog" v-model:busy="busy" @changed="load"/></main></template>
