<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { adminBookings, adminComments, adminUsers, adminLogs, operationStatus, type OperationKind, type AdminUser, type AiLog } from '@/api/modules/operations'
import Pagination from '@/components/common/Pagination.vue'
const props=defineProps<{kind:OperationKind}>()
const rows=ref<(BookingVO|CommentVO|AdminUser|AiLog)[]>([]),total=ref(0),current=ref(1),status=ref(-1),keyword=ref(''),targetId=ref<string>(''),loading=ref(false),busy=ref(false)
const title=computed(()=>({bookings:'预约管理',comments:'评论管理',users:'用户管理',logs:'AI调用日志'}[props.kind]))
const labels=computed(()=>props.kind==='bookings'?['待确认','已确认','已取消','已完成']:props.kind==='comments'?['已隐藏','已显示']:['已停用','已启用'])
let version=0
async function load(){const v=++version;if(targetId.value&&(!/^[1-9]\d*$/.test(targetId.value)||!Number.isSafeInteger(Number(targetId.value)))){ElMessage.warning('筛选ID须为正整数');return}loading.value=true;try{const params={current:current.value,size:20,status:status.value<0?undefined:status.value,keyword:keyword.value.trim()||undefined,routeId:targetId.value?Number(targetId.value):undefined,userId:targetId.value?Number(targetId.value):undefined};const p=await ({bookings:adminBookings,comments:adminComments,users:adminUsers,logs:adminLogs}[props.kind])(params);if(v!==version)return;rows.value=p.records;total.value=p.total;if(!p.records.length&&current.value>1){current.value=Math.max(1,p.pages);await load()}}catch{}finally{if(v===version)loading.value=false}}
function search(){current.value=1;void load()}
async function act(id:number,next:number){if(busy.value)return;try{await ElMessageBox.confirm(props.kind==='users'?`确认${next?'启用':'停用'}此账号？停用会使现有登录失效，重新启用后须重新登录。`:`确认更新为“${labels.value[next]}”？`,title.value,{type:'warning'});busy.value=true;await operationStatus(props.kind,id,next);ElMessage.success('操作已保存');await load()}catch{}finally{busy.value=false}}
watch(()=>props.kind,()=>{++version;rows.value=[];total.value=0;current.value=1;status.value=-1;keyword.value='';targetId.value='';void load()})
onMounted(load)
</script>
<template><main class="admin-page"><h1>{{title}}</h1><p class="admin-help" v-if="kind==='bookings'">待确认预约可确认或取消；已确认可标记完成。下架路线的历史预约仍可管理。</p><p class="admin-help" v-else-if="kind==='comments'">隐藏评论后前台不可见，评分统计同步更新；支持恢复显示。</p><p class="admin-help" v-else-if="kind==='users'">可查询账号和启停普通用户。管理员账号受保护；账号重新启用后须重新登录。</p><p class="admin-help" v-else>查看调用时间、结果、降级状态与耗时。密钥、用户提示词及原始模型响应不在此展示。</p><section class="admin-panel" v-loading="loading"><div class="admin-tools"><el-input v-if="kind==='users'" v-model="keyword" aria-label="搜索用户" placeholder="用户名或昵称" clearable @keyup.enter="search"/><el-input v-else v-model="targetId" :aria-label="kind==='logs'?'筛选用户ID':'筛选路线ID'" :placeholder="kind==='logs'?'用户ID（可选）':'路线ID（可选）'" clearable @keyup.enter="search"/><el-select v-if="kind!=='logs'" v-model="status" aria-label="管理状态筛选" @change="search"><el-option label="全部状态" :value="-1"/><el-option v-for="(label,i) in labels" :key="i" :label="label" :value="i"/></el-select><el-button @click="search">查询</el-button><el-button @click="load">刷新</el-button></div>
  <el-table v-if="kind==='bookings'" :data="rows" empty-text="暂无预约"><el-table-column prop="bookingNo" label="预约编号" min-width="210"/><el-table-column prop="routeTitle" label="路线" min-width="160"/><el-table-column prop="travelDate" label="出行日期" width="120"/><el-table-column prop="peopleNum" label="人数" width="70"/><el-table-column prop="contactName" label="联系人" width="110"/><el-table-column prop="contactPhone" label="电话" width="140"/><el-table-column label="状态" width="100"><template #default="s">{{labels[s.row.status]}}</template></el-table-column><el-table-column label="操作" min-width="150"><template #default="s"><template v-if="s.row.status===0"><el-button link :disabled="busy" @click="act(s.row.bookingId,1)">确认预约</el-button><el-button link type="danger" :disabled="busy" @click="act(s.row.bookingId,2)">取消预约</el-button></template><el-button v-else-if="s.row.status===1" link :disabled="busy" @click="act(s.row.bookingId,3)">标记完成</el-button><span v-else>已结束</span></template></el-table-column></el-table>
  <el-table v-else-if="kind==='comments'" :data="rows" empty-text="暂无评论"><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="routeId" label="路线ID" width="90"/><el-table-column prop="userNickname" label="用户" width="120"/><el-table-column prop="score" label="评分" width="70"/><el-table-column prop="content" label="内容" min-width="240"><template #default="s"><span class="admin-text">{{s.row.content}}</span><div v-if="s.row.images?.length"><el-image v-for="url in s.row.images" :key="url" :src="url" class="admin-cover" :preview-src-list="s.row.images" preview-teleported/></div></template></el-table-column><el-table-column label="状态" width="100"><template #default="s">{{labels[s.row.status]}}</template></el-table-column><el-table-column label="操作" width="110"><template #default="s"><el-button link :disabled="busy" @click="act(s.row.id,s.row.status?0:1)">{{s.row.status?'隐藏':'恢复显示'}}</el-button></template></el-table-column></el-table>
  <el-table v-else-if="kind==='users'" :data="rows" empty-text="暂无用户"><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="username" label="用户名" min-width="140"/><el-table-column prop="nickname" label="昵称" min-width="130"/><el-table-column prop="city" label="城市" width="100"/><el-table-column label="角色" width="100"><template #default="s">{{s.row.role==='ADMIN'?'管理员':'普通用户'}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s">{{labels[s.row.status]}}</template></el-table-column><el-table-column prop="createTime" label="注册时间" min-width="175"/><el-table-column label="操作" width="110"><template #default="s"><el-button v-if="s.row.role==='USER'" link :type="s.row.status?'danger':'primary'" :disabled="busy" @click="act(s.row.id,s.row.status?0:1)">{{s.row.status?'停用':'启用'}}</el-button><span v-else>受保护</span></template></el-table-column></el-table>
  <el-table v-else :data="rows" empty-text="暂无调用记录"><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="userId" label="用户ID" width="95"/><el-table-column prop="scene" label="场景" min-width="160"/><el-table-column prop="model" label="模型" min-width="160"/><el-table-column prop="costMs" label="耗时(ms)" width="110"/><el-table-column label="结果" width="100"><template #default="s">{{s.row.success?'成功':'失败'}}</template></el-table-column><el-table-column label="降级" width="85"><template #default="s">{{s.row.isFallback?'是':'否'}}</template></el-table-column><el-table-column prop="createTime" label="时间" min-width="180"/></el-table>
  <div class="admin-pagination"><Pagination :total="total" :current="current" :size="20" @change="p=>{current=p;load()}"/></div></section></main></template>
