<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { catalogRoutes, catalogRoute, saveRoute, deleteRoute, routeStatus, routeTop, catalogDestinations, catalogDestination, catalogAttractions, type CatalogRoute, type RouteInput, type CatalogDay, type CatalogItem } from '@/api/modules/catalog'
import Pagination from '@/components/common/Pagination.vue'
import AdminImageField from '@/components/common/AdminImageField.vue'
const rows=ref<CatalogRoute[]>([]),current=ref(1),total=ref(0),keyword=ref(''),status=ref(-1),loading=ref(false),busy=ref(false),visible=ref(false),editing=ref<number>(),tags=ref(''),parents=ref<DestinationVO[]>([]),spots=ref<AttractionVO[]>([])
const item=():CatalogItem=>({title:'',timePoint:'09:00',attractionId:0,activity:'',transport:'',hotel:'',meal:'',durationMin:60,cost:0,tips:''})
const day=():CatalogDay=>({title:'',summary:'',items:[item()]})
const fresh=():RouteInput=>({title:'',subtitle:'',coverImg:'',destinationId:0,days:1,price:0,difficulty:1,tags:[],highlights:'',notice:'',recommendWeight:0.5,isTop:0,quotaPerDay:20,status:0,dayList:[day()]})
const form=ref(fresh());let version=0,parentVersion=0,spotVersion=0
async function load(){const v=++version;loading.value=true;try{const p=await catalogRoutes({current:current.value,keyword:keyword.value.trim()||undefined,status:status.value<0?undefined:status.value});if(v!==version)return;rows.value=p.records;total.value=p.total;if(!p.records.length&&current.value>1){current.value=Math.max(1,p.pages);await load()}}catch{}finally{if(v===version)loading.value=false}}
function search(){current.value=1;void load()}
async function lookup(keyword=''){const v=++parentVersion;try{const p=await catalogDestinations({current:1,size:100,keyword:keyword||undefined});if(v!==parentVersion)return;parents.value=p.records;if(form.value.destinationId&&!parents.value.some(p=>p.id===form.value.destinationId))parents.value.unshift(await catalogDestination(form.value.destinationId))}catch{}}
async function loadSpots(reset=false){const v=++spotVersion;spots.value=[];if(reset)form.value.dayList.forEach(d=>d.items.forEach(i=>i.attractionId=0));if(!form.value.destinationId)return;try{const list=await catalogAttractions(form.value.destinationId);if(v===spotVersion)spots.value=list}catch{}}
async function edit(row?:CatalogRoute){if(busy.value)return;busy.value=true;try{editing.value=row?.id;form.value=row?await catalogRoute(row.id):fresh();tags.value=form.value.tags.join('，');await lookup();await loadSpots();visible.value=true}catch{}finally{busy.value=false}}
async function save(){if(busy.value)return;if(!form.value.title.trim()||!form.value.coverImg.trim()||!form.value.destinationId||form.value.dayList.some(d=>!d.title.trim()||!d.items.length||d.items.some(i=>!i.title.trim()))){ElMessage.warning('请填写路线标题、封面、目的地以及每天和每项行程的标题');return}busy.value=true;try{await saveRoute({...form.value,days:form.value.dayList.length,tags:tags.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean)},editing.value);visible.value=false;ElMessage.success('路线已保存');await load()}catch{}finally{busy.value=false}}
async function act(row:CatalogRoute,action:'delete'|'status'|'top'){if(busy.value)return;try{await ElMessageBox.confirm(action==='delete'?'有预约记录的路线只能下架，不能删除。确认删除？':`确认${action==='top'?(row.isTop?'取消置顶':'置顶'):(row.status?'下架':'上架')}“${row.title}”？`,'更新路线',{type:'warning'});busy.value=true;if(action==='delete')await deleteRoute(row.id);else if(action==='status')await routeStatus(row.id,row.status?0:1);else await routeTop(row.id,row.isTop?0:1);await load();ElMessage.success('路线已更新')}catch{}finally{busy.value=false}}
function move<T>(list:T[],from:number,to:number){if(to<0||to>=list.length)return;const entry=list.splice(from,1)[0];if(entry!==undefined)list.splice(to,0,entry)}
onMounted(load)
</script>
<template><main class="admin-page"><h1>路线与行程</h1><p class="admin-help">维护路线价格、名额、推荐权重和每日行程；只有已上架目的地的路线可以上架。</p><section class="admin-panel" v-loading="loading"><div class="admin-tools"><el-input v-model="keyword" aria-label="搜索路线" placeholder="路线标题" clearable @keyup.enter="search"/><el-select v-model="status" aria-label="路线状态筛选" @change="search"><el-option label="全部状态" :value="-1"/><el-option label="已上架" :value="1"/><el-option label="已下架" :value="0"/></el-select><el-button @click="search">查询</el-button><el-button @click="load">刷新</el-button><el-button type="primary" :disabled="busy" @click="edit()">新增路线</el-button></div><el-table :data="rows" empty-text="暂无路线"><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="title" label="标题" min-width="180"/><el-table-column prop="destinationName" label="目的地" width="110"/><el-table-column prop="days" label="天数" width="70"/><el-table-column prop="price" label="价格" width="90"/><el-table-column label="状态" width="100"><template #default="s">{{s.row.status?'已上架':'已下架'}}{{s.row.isTop?' · 置顶':''}}</template></el-table-column><el-table-column label="操作" min-width="250"><template #default="s"><div class="admin-row-actions"><el-button link :disabled="busy" @click="edit(s.row)">编辑</el-button><el-button link :disabled="busy" @click="act(s.row,'status')">{{s.row.status?'下架':'上架'}}</el-button><el-button link :disabled="busy" @click="act(s.row,'top')">{{s.row.isTop?'取消置顶':'置顶'}}</el-button><el-button link type="danger" :disabled="busy" @click="act(s.row,'delete')">删除</el-button></div></template></el-table-column></el-table><div class="admin-pagination"><Pagination :total="total" :current="current" :size="20" @change="p=>{current=p;load()}"/></div></section>
  <el-dialog v-model="visible" :title="editing?'编辑路线':'新增路线'" class="admin-dialog route-dialog" width="min(1060px, calc(100vw - 24px))" :close-on-click-modal="!busy" :close-on-press-escape="!busy" :show-close="!busy"><el-form label-position="top" :disabled="busy"><div class="admin-form"><el-form-item label="标题（必填）"><el-input v-model="form.title" aria-label="路线标题" maxlength="200"/></el-form-item><el-form-item label="副标题"><el-input v-model="form.subtitle" aria-label="路线副标题" maxlength="255"/></el-form-item><el-form-item label="目的地（可搜索，必填）"><el-select v-model="form.destinationId" aria-label="路线目的地" filterable remote :remote-method="lookup" @change="loadSpots(true)"><el-option v-for="p in parents" :key="p.id" :label="`${p.name}${p.status?'':'（已下架）'}`" :value="p.id"/></el-select></el-form-item><el-form-item label="价格（人均）"><el-input-number v-model="form.price" aria-label="路线价格" :min="0" :max="99999999.99" :precision="2"/></el-form-item><el-form-item label="难度（1—5）"><el-input-number v-model="form.difficulty" aria-label="路线难度" :min="1" :max="5"/></el-form-item><el-form-item label="每日名额"><el-input-number v-model="form.quotaPerDay" aria-label="每日名额" :min="1" :max="10000"/></el-form-item><el-form-item label="推荐权重（0—1）"><el-input-number v-model="form.recommendWeight" aria-label="推荐权重" :min="0" :max="1" :step="0.1" :precision="4"/></el-form-item><el-form-item label="上架状态"><el-select v-model="form.status" aria-label="路线保存状态"><el-option label="已下架" :value="0"/><el-option label="已上架" :value="1"/></el-select></el-form-item><el-form-item label="置顶"><el-switch v-model="form.isTop" :active-value="1" :inactive-value="0" aria-label="路线置顶"/></el-form-item><el-form-item label="标签（最多5个，逗号分隔）"><el-input v-model="tags" aria-label="路线标签"/></el-form-item><el-form-item label="封面（必填）" class="wide"><AdminImageField v-model="form.coverImg"/></el-form-item><el-form-item label="路线亮点"><el-input v-model="form.highlights" aria-label="路线亮点" type="textarea" maxlength="10000"/></el-form-item><el-form-item label="注意事项"><el-input v-model="form.notice" aria-label="路线注意事项" type="textarea" maxlength="10000"/></el-form-item></div>
  <h2>每日行程 · {{form.dayList.length}}天</h2><p class="admin-note">最多30天，每天1—15项。调整顺序后保存，天数和序号会自动生成。删除景点后，已有条目的文字快照可保留，将关联景点改为自定义即可。</p>
  <section v-for="(d,di) in form.dayList" :key="di" class="route-day" :data-day="di"><div class="day-heading"><h3>第{{di+1}}天</h3><div><el-button :disabled="di===0" @click="move(form.dayList,di,di-1)">前移一天</el-button><el-button :disabled="di===form.dayList.length-1" @click="move(form.dayList,di,di+1)">后移一天</el-button><el-button type="danger" :disabled="form.dayList.length===1" @click="form.dayList.splice(di,1)">删除本天</el-button></div></div><div class="admin-form"><el-form-item label="当天标题（必填）"><el-input v-model="d.title" :aria-label="`第${di+1}天标题`" maxlength="100"/></el-form-item><el-form-item label="当天概要"><el-input v-model="d.summary" :aria-label="`第${di+1}天概要`" maxlength="255"/></el-form-item></div>
  <div v-for="(i,ii) in d.items" :key="ii" class="route-item"><div class="item-heading"><strong>行程{{ii+1}}</strong><div><el-button :disabled="ii===0" @click="move(d.items,ii,ii-1)">上移</el-button><el-button :disabled="ii===d.items.length-1" @click="move(d.items,ii,ii+1)">下移</el-button><el-button type="danger" :disabled="d.items.length===1" @click="d.items.splice(ii,1)">删除行程</el-button></div></div><div class="admin-form"><el-form-item label="行程标题（必填）"><el-input v-model="i.title" :aria-label="`第${di+1}天行程${ii+1}标题`" maxlength="100"/></el-form-item><el-form-item label="关联景点"><el-select v-model="i.attractionId" :aria-label="`第${di+1}天行程${ii+1}景点`"><el-option label="自定义行程（不关联景点）" :value="0"/><el-option v-for="s in spots" :key="s.id" :label="s.name+(s.status?'':'（已下架）')" :value="s.id" :disabled="s.status!==1"/></el-select></el-form-item><el-form-item label="时间（HH:mm）"><el-input v-model="i.timePoint" placeholder="09:00" maxlength="5"/></el-form-item><el-form-item label="活动"><el-input v-model="i.activity" maxlength="255"/></el-form-item><el-form-item label="时长（分钟）"><el-input-number v-model="i.durationMin" :min="0" :max="1440"/></el-form-item><el-form-item label="费用"><el-input-number v-model="i.cost" :min="0" :max="99999999.99" :precision="2"/></el-form-item><el-form-item label="交通"><el-input v-model="i.transport" maxlength="50"/></el-form-item><el-form-item label="住宿"><el-input v-model="i.hotel" maxlength="100"/></el-form-item><el-form-item label="餐饮"><el-input v-model="i.meal" maxlength="100"/></el-form-item><el-form-item label="提示"><el-input v-model="i.tips" maxlength="255"/></el-form-item></div></div><el-button :disabled="d.items.length>=15" @click="d.items.push(item())">新增行程</el-button></section><el-button :disabled="form.dayList.length>=30" @click="form.dayList.push(day())">新增一天</el-button></el-form><template #footer><el-button :disabled="busy" @click="visible=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存路线</el-button></template></el-dialog></main></template>
<style scoped>.route-day{border:1px solid #dce5ef;border-radius:8px;padding:16px;margin:16px 0}.route-item{padding:14px;background:#f6f8fb;border-radius:8px;margin-bottom:12px}.day-heading,.item-heading{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.day-heading>div,.item-heading>div{display:flex;flex-wrap:wrap;gap:4px}.day-heading h3{margin:0}.el-button+.el-button{margin-left:0}</style>
