// Real Edge UI acceptance; only generated accounts/content are written or removed.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),base='http://127.0.0.1:5173',api=base+'/api';
const out=path.join(root,'docs/dev/evidence/admin',new Date().toISOString().replace(/[:.]/g,'-')+'-browser');
const checks=[],errors=[],users=[],destIds=[],routeIds=[],bannerIds=[],files=[];
const marker='AdminUI-'+crypto.randomUUID().slice(0,8)+'中文旅行',password='AdminUiPass123';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAIAAAASFvFNAAAAFElEQVR4nGOUqzjBAAZMEIqBgQEAGC4BYoYfTS8AAAAASUVORK5CYII=','base64');
let browser,page,stage='start';
function save(){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:'REAL_EDGE_ADMIN_HTTP_MYSQL_REDIS',stage,fixtures:{users,destIds,routeIds,bannerIds,files},checks,pageErrors:errors,summary:{total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length}},null,2));}
function check(name,actual,expected){checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
function sql(query){return execFileSync('mysql',['-u','root','-N','-B','--default-character-set=utf8mb4','trip_llm','-e',query],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
async function call(path,body,method='GET',token=''){const r=await fetch(api+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json()};}
async function user(admin){const name='adm_ui_'+crypto.randomUUID().replaceAll('-','').slice(0,10);const r=await call('/auth/register',{username:name,password,nickname:marker},'POST');if(r.body.code!==200)throw Error('Registration failed');const u={name,id:Number(sql(`SELECT id FROM sys_user WHERE username='${name}'`))};users.push(u);save();if(admin)sql(`UPDATE sys_user SET role='ADMIN' WHERE id=${u.id}`);return u;}
function watch(p){p.setDefaultTimeout(12000);p.on('pageerror',e=>{errors.push(e.message);save()});}
async function login(p,u,route){await p.goto(base+'/login?redirect='+route);await p.getByPlaceholder('user1001').fill(u.name);await p.getByPlaceholder('123456',{exact:true}).fill(password);await p.getByRole('button',{name:'登 录',exact:true}).click();await p.waitForURL(url=>url.pathname===route);}
async function choose(label,text,scope=page){await page.bringToFront();const c=scope.getByRole('combobox',{name:label,exact:true});await c.focus();await c.press('ArrowDown');const id=await c.getAttribute('aria-controls');await page.locator('#'+id).getByRole('option',{name:text,exact:true}).click();}
async function action(button,ending,method){const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith(ending)&&r.request().method()===method).then(r=>r.json());const [data]=await Promise.all([response,button.click()]);return data;}
async function confirm(button,ending){await button.click();const box=page.getByRole('dialog');const data=await action(box.getByRole('button',{name:'确定',exact:true}),ending,'PUT');await box.waitFor({state:'hidden'});return data;}
async function search(label,value){await page.getByLabel(label,{exact:true}).fill(value);await page.getByRole('button',{name:'查询',exact:true}).click();}
function row(text){return page.locator('.el-table__row').filter({hasText:text}).first();}
async function go(route,heading){stage=route;save();await page.goto(base+route);await page.getByRole('heading',{name:heading,exact:true}).waitFor();await page.locator('.el-loading-mask').waitFor({state:'hidden'});}
async function settleDialog(){await page.waitForFunction(()=>Array.from(document.querySelectorAll('.el-overlay')).filter(e=>getComputedStyle(e).display!=='none').every(e=>Number(getComputedStyle(e).opacity)>=0.999&&e.getAnimations({subtree:true}).every(a=>a.playState!=='running')));}
async function run(){try{
  sql('SELECT 1');const regular=await user(false),admin=await user(true);
  const userLogin=await call('/auth/login',{username:regular.name,password},'POST'),token=userLogin.body.data.accessToken;
  browser=await chromium.launch({channel:'msedge',headless:true});const ac=await browser.newContext({viewport:{width:1440,height:1000}});page=await ac.newPage();watch(page);
  await login(page,admin,'/admin');await page.getByRole('heading',{name:'运营概览',exact:true}).waitFor();check('admin navigation contains all sections',await page.getByRole('navigation',{name:'后台导航'}).getByRole('link').count(),8);
  await go('/admin/destinations','目的地与景点');await page.getByRole('button',{name:'新增目的地',exact:true}).click();let dialog=page.getByRole('dialog');
  await dialog.getByRole('button',{name:'保存目的地',exact:true}).click();await page.getByText('请填写名称、省份和封面图片',{exact:true}).waitFor();check('empty destination form explained',true,true);
  await dialog.getByLabel('目的地名称',{exact:true}).fill(marker);await dialog.getByLabel('目的地省份',{exact:true}).fill('TestProvince');await dialog.getByLabel('目的地城市',{exact:true}).fill('TestCity');
  const uploading=page.waitForResponse(r=>r.url().endsWith('/api/file/upload')).then(r=>r.json());await dialog.getByLabel('上传图片',{exact:true}).setInputFiles({name:'admin.png',mimeType:'image/png',buffer:png});const uploaded=await uploading;check('admin cover real upload',uploaded.code,200);if(!/^[a-f0-9]{32}\.png$/.test(uploaded.data.name))throw Error('Invalid fixture image');files.push(uploaded.data.name);save();await dialog.locator('.image-uploader img').waitFor();
  const created=await action(dialog.getByRole('button',{name:'保存目的地',exact:true}),'/api/admin/catalog/destinations','POST');check('destination created from UI',created.code,200);const did=created.data;destIds.push(did);save();await dialog.waitFor({state:'hidden'});await search('搜索目的地',marker);await row(marker).waitFor();
  check('new destination defaults offline',await row(marker).getByText('已下架',{exact:true}).isVisible(),true);check('destination publish from UI',(await confirm(row(marker).getByRole('button',{name:'上架',exact:true}),`/api/admin/catalog/destinations/${did}/status`)).code,200);
  await row(marker).getByRole('button',{name:'编辑',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('目的地简介',{exact:true}).fill('Updated by admin browser');check('destination edit from UI',(await action(dialog.getByRole('button',{name:'保存目的地',exact:true}),`/api/admin/catalog/destinations/${did}`,'PUT')).code,200);await dialog.waitFor({state:'hidden'});check('destination edit stored',sql(`SELECT intro FROM destination WHERE id=${did}`),'Updated by admin browser');
  await row(marker).getByRole('button',{name:'景点',exact:true}).click();await page.getByRole('button',{name:'新增景点',exact:true}).click();dialog=page.locator('.el-dialog').filter({hasText:'新增景点'});await dialog.getByLabel('景点名称',{exact:true}).fill(marker+'-spot');await dialog.getByLabel('景点门票',{exact:true}).fill('35');
  const spot=await action(dialog.getByRole('button',{name:'保存景点',exact:true}),`/api/admin/catalog/destinations/${did}/attractions`,'POST');check('attraction created from UI',spot.code,200);await dialog.waitFor({state:'hidden'});await row(marker+'-spot').waitFor();await row(marker+'-spot').getByRole('button',{name:'编辑',exact:true}).click();dialog=page.locator('.el-dialog').filter({hasText:'编辑景点'});await dialog.getByLabel('景点简介',{exact:true}).fill('Updated spot description');check('attraction edit from UI',(await action(dialog.getByRole('button',{name:'保存景点',exact:true}),`/api/admin/catalog/attractions/${spot.data}`,'PUT')).code,200);await dialog.waitFor({state:'hidden'});
  await go('/admin/routes','路线与行程');await page.getByRole('button',{name:'新增路线',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('路线标题',{exact:true}).fill(marker+'-route');await dialog.getByLabel('封面图片地址',{exact:true}).fill(uploaded.data.url);await choose('路线目的地',marker,dialog);await dialog.getByLabel('路线价格',{exact:true}).fill('350');await choose('路线保存状态','已上架',dialog);await dialog.getByLabel('第1天标题',{exact:true}).fill('Day one');await dialog.getByLabel('第1天行程1标题',{exact:true}).fill('Visit spot');await choose('第1天行程1景点',marker+'-spot',dialog);
  await dialog.getByRole('button',{name:'新增一天',exact:true}).click();await dialog.getByLabel('第2天标题',{exact:true}).fill('Day two');await dialog.getByLabel('第2天行程1标题',{exact:true}).fill('Custom walk');await dialog.locator('[data-day="1"]').getByRole('button',{name:'前移一天',exact:true}).click();check('day reorder on UI',await dialog.getByLabel('第1天标题',{exact:true}).inputValue(),'Day two');
  const route=await action(dialog.getByRole('button',{name:'保存路线',exact:true}),'/api/admin/catalog/routes','POST');check('route created from UI',route.code,200);const rid=route.data;routeIds.push(rid);save();await dialog.waitFor({state:'hidden'});await search('搜索路线',marker);await row(marker+'-route').waitFor();check('day ordering stored',sql(`SELECT title FROM route_day WHERE route_id=${rid} ORDER BY day_index`),'Day two\r\nDay one');
  await row(marker+'-route').getByRole('button',{name:'编辑',exact:true}).click();dialog=page.getByRole('dialog');check('route editor reloads saved day',await dialog.getByLabel('第1天标题',{exact:true}).inputValue(),'Day two');await dialog.getByLabel('推荐权重',{exact:true}).fill('0.7');check('route edit from UI',(await action(dialog.getByRole('button',{name:'保存路线',exact:true}),`/api/admin/catalog/routes/${rid}`,'PUT')).code,200);await dialog.waitFor({state:'hidden'});check('route top from UI',(await confirm(row(marker+'-route').getByRole('button',{name:'置顶',exact:true}),`/api/admin/catalog/routes/${rid}/top`)).code,200);
  await go('/admin/banners','首页轮播');await page.getByRole('button',{name:'新增轮播',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('轮播标题',{exact:true}).fill(marker+'-banner');await dialog.getByLabel('轮播图片地址',{exact:true}).fill(uploaded.data.url);await choose('轮播跳转类型','路线',dialog);await dialog.getByLabel('轮播跳转目标',{exact:true}).fill(String(rid));await choose('轮播保存状态','已启用',dialog);
  const banner=await action(dialog.getByRole('button',{name:'保存轮播',exact:true}),'/api/admin/banner','POST');check('banner created from UI',banner.code,200);if(banner.code!==200)throw Error('Enable banner failed');const bid=banner.data;bannerIds.push(bid);save();await dialog.waitFor({state:'hidden'});await row(marker+'-banner').waitFor();await page.goto(base+'/');await page.locator('.home-banners').waitFor();check('homepage displays configured banner',await page.locator('.banner-slide').filter({hasText:marker+'-banner'}).count(),1);check('homepage banner has route link',await page.locator('.banner-slide').filter({hasText:marker+'-banner'}).getAttribute('href'),'/route/'+rid);
  const when=new Date(Date.now()+5*86400000).toISOString().slice(0,10);const booking=await call('/interaction/booking',{routeId:rid,travelDate:when,peopleNum:1,contactName:marker,contactPhone:'13800000000'},'POST',token);check('real booking fixture',booking.body.code,200);const comment=await call('/interaction/comment',{routeId:rid,score:5,content:marker+' comment <script>alert(1)</script>',images:[]},'POST',token);check('real comment fixture',comment.body.code,200);
  await go('/admin/routes','路线与行程');await search('搜索路线',marker);check('route offline from UI',(await confirm(row(marker+'-route').getByRole('button',{name:'下架',exact:true}),`/api/admin/catalog/routes/${rid}/status`)).code,200);
  check('offline route hidden from public',(await call('/route/'+rid)).body.code,2001);check('offline banner hidden',(await call('/banner/list')).body.data.some(b=>b.id===bid),false);
  await go('/admin/bookings','预约管理');await search('筛选路线ID',String(rid));await row(marker).waitFor();check('offline historical booking confirmed',(await confirm(row(marker).getByRole('button',{name:'确认预约',exact:true}),`/api/admin/interaction/booking/${booking.body.data.bookingId}/status`)).code,200);await row(marker).getByRole('button',{name:'标记完成',exact:true}).waitFor();check('confirmed booking completed',(await confirm(row(marker).getByRole('button',{name:'标记完成',exact:true}),`/api/admin/interaction/booking/${booking.body.data.bookingId}/status`)).code,200);
  await go('/admin/comments','评论管理');await search('筛选路线ID',String(rid));await row(marker).waitFor();check('comment script remains literal',(await row(marker).innerText()).includes('<script>alert(1)</script>'),true);check('offline comment hidden from UI',(await confirm(row(marker).getByRole('button',{name:'隐藏',exact:true}),`/api/admin/interaction/comment/${comment.body.data.id}/status`)).code,200);await row(marker).getByRole('button',{name:'恢复显示',exact:true}).waitFor();check('comment restored from UI',(await confirm(row(marker).getByRole('button',{name:'恢复显示',exact:true}),`/api/admin/interaction/comment/${comment.body.data.id}/status`)).code,200);
  await go('/admin/users','用户管理');await search('搜索用户',regular.name);await row(regular.name).waitFor();check('disable account from UI',(await confirm(row(regular.name).getByRole('button',{name:'停用',exact:true}),`/api/admin/user/${regular.id}/status`)).code,200);check('disabled token denied',(await call('/user/profile',undefined,'GET',token)).status,401);check('enable account from UI',(await confirm(row(regular.name).getByRole('button',{name:'启用',exact:true}),`/api/admin/user/${regular.id}/status`)).code,200);check('old session remains revoked',(await call('/user/profile',undefined,'GET',token)).status,401);
  await go('/admin/logs','AI调用日志');await search('筛选用户ID',String(regular.id));await page.getByText('暂无调用记录',{exact:true}).waitFor();check('logs empty state',true,true);
  const uc=await browser.newContext();const up=await uc.newPage();watch(up);await login(up,regular,'/user/profile');await up.goto(base+'/admin/routes');await up.waitForURL(url=>url.pathname==='/');check('ordinary user cannot enter nested admin route',new URL(up.url()).pathname,'/');await uc.close();
  await page.setViewportSize({width:390,height:844});await go('/admin/destinations','目的地与景点');await search('搜索目的地',marker);await row(marker).getByRole('button',{name:'编辑',exact:true}).click();dialog=page.locator('.el-dialog');await dialog.waitFor();await settleDialog();const box=await dialog.boundingBox();check('mobile destination dialog fits',box.x>=0&&box.x+box.width<=391,true);check('mobile page has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);check('mobile destination dialog is opaque',await dialog.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');await page.screenshot({path:path.join(out,'destination-mobile.png'),fullPage:true,animations:'disabled'});await dialog.getByRole('button',{name:'取消',exact:true}).click();
  await go('/admin/routes','路线与行程');await search('搜索路线',marker);await row(marker+'-route').getByRole('button',{name:'编辑',exact:true}).click();dialog=page.locator('.el-dialog');await dialog.waitFor();await settleDialog();const rb=await dialog.boundingBox();check('mobile route editor fits',rb.x>=0&&rb.x+rb.width<=391,true);await page.screenshot({path:path.join(out,'route-mobile.png'),fullPage:true,animations:'disabled'});await dialog.getByRole('button',{name:'取消',exact:true}).click();
  await page.setViewportSize({width:1440,height:1000});await go('/admin/banners','首页轮播');await row(marker+'-banner').getByRole('button',{name:'编辑',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('轮播标题',{exact:true}).fill(marker+'-banner-edited');check('banner edit from UI',(await action(dialog.getByRole('button',{name:'保存轮播',exact:true}),`/api/admin/banner/${bid}`,'PUT')).code,200);await dialog.waitFor({state:'hidden'});check('banner stopped from UI',(await confirm(row(marker+'-banner-edited').getByRole('button',{name:'停用',exact:true}),`/api/admin/banner/${bid}`)).code,200);
  await row(marker+'-banner-edited').getByRole('button',{name:'删除',exact:true}).click();check('banner deleted from UI',(await action(page.getByRole('dialog').getByRole('button',{name:'确定',exact:true}),`/api/admin/banner/${bid}`,'DELETE')).code,200);
  await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'退出登录',exact:true}).click();check('admin logout revokes session',(await action(page.getByRole('dialog').getByRole('button',{name:'确定',exact:true}),'/api/auth/logout','POST')).code,200);await page.waitForURL(url=>url.pathname==='/login');await page.goto(base+'/admin/routes');await page.waitForURL(url=>url.pathname==='/login');check('admin logout requires login again',new URL(page.url()).pathname,'/login');
}catch(e){check('browser execution completed',e.message,'no exception');if(page)try{await page.screenshot({path:path.join(out,'failure.png'),fullPage:true})}catch{}}
finally{
  if(browser)await browser.close();try{
    for(const bid of bannerIds)sql(`DELETE FROM banner WHERE id=${bid}`);
    for(const rid of routeIds){sql(`DELETE FROM route_booking WHERE route_id=${rid}; DELETE FROM route_comment WHERE route_id=${rid}; DELETE FROM route_like WHERE route_id=${rid}; DELETE FROM route_favorite WHERE route_id=${rid}; DELETE ri FROM route_item ri JOIN route_day rd ON rd.id=ri.route_day_id WHERE rd.route_id=${rid}; DELETE FROM route_day WHERE route_id=${rid}; DELETE FROM route WHERE id=${rid}`);check('temporary route removed',sql(`SELECT COUNT(*) FROM route WHERE id=${rid}`),'0');}
    for(const did of destIds)sql(`DELETE FROM attraction WHERE destination_id=${did}; DELETE FROM destination WHERE id=${did}`);
    for(const u of users){sql(`DELETE FROM user_behavior WHERE user_id=${u.id}; DELETE FROM user_preference WHERE user_id=${u.id}; DELETE FROM sys_user WHERE id=${u.id} AND username='${u.name}'`);const prefix=`trip:auth:session:{${u.id}}:`;for(const key of execFileSync('redis-cli',['--scan','--pattern',prefix+'*'],{encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean)){if(!key.startsWith(prefix))throw Error('Unexpected key');execFileSync('redis-cli',['DEL',key]);}check('temporary user removed',sql(`SELECT COUNT(*) FROM sys_user WHERE id=${u.id}`),'0');}
    const uploads=path.resolve(root,'trip-server/uploads');for(const name of files){if(!/^[a-f0-9]{32}\.png$/.test(name))throw Error('Unexpected upload');const target=path.resolve(uploads,name);if(path.dirname(target)!==uploads)throw Error('Unexpected upload path');if(fs.existsSync(target))fs.unlinkSync(target);check('temporary image removed',fs.existsSync(target),false);}
    check('fixture cleanup completed',true,true);
  }catch(e){check('fixture cleanup completed',e.message,'no exception');}
  check('no unhandled page errors',errors.length,0);save();const passed=checks.filter(c=>c.passed).length;console.log(`${passed}/${checks.length} passed; ${out}`);process.exitCode=passed===checks.length?0:1;
}}
run();
