// Real Edge/app/HTTP/MySQL/Redis; only network failure/delay are controlled. No model calls.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),{cleanSessions}=require('./redis_fixture.cjs');
const base='http://127.0.0.1:5173',password='AnalyticsUi123',users=[],dids=[],rids=[],checks=[],errors=[],warnings=[],requests=[],marker='aui'+Date.now(),out=path.resolve(__dirname,'../../docs/dev/evidence/analysis',new Date().toISOString().replace(/[:.]/g,'-')+'-browser');
fs.mkdirSync(out,{recursive:true});let browser,page,phase='RUNNING';
function sql(q){return execFileSync('mysql',['-u','root','-N','-B','--default-character-set=utf8mb4','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
function save(){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:'REAL_EDGE_ANALYTICS_WITH_OWN_SQL_FIXTURES',boundary:'Live stats; controlled network error and delayed real response only; no model calls.',phase,checks,errors,warnings,requests,summary:{total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length}},null,2));}
function check(name,actual,expected){checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
async function login(user,target){await page.goto(base+'/login?redirect='+encodeURIComponent(target));await page.getByPlaceholder('user1001').fill(user.name);await page.getByPlaceholder('123456',{exact:true}).fill(password);await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL(u=>u.pathname===target);}
async function ready(){await page.getByTestId('analysis-metrics').waitFor();await page.waitForFunction(()=>document.querySelector('[data-testid="analytics-page"]')?.getAttribute('aria-busy')==='false');}
async function choose(label,value){await page.getByRole('combobox',{name:label,exact:true}).focus();await page.getByRole('combobox',{name:label,exact:true}).press('ArrowDown');await page.getByRole('option',{name:value,exact:true}).click();await ready();}
function dest(suffix){const id=Number(sql(`INSERT INTO destination(name,province,city,longitude,latitude,cover_img,status) VALUES('${marker+suffix}','验收省','验收市',120,30,'/fixture.png',0);SELECT LAST_INSERT_ID()`));dids.push(id);return id;}
function route(d,title,price){const id=Number(sql(`INSERT INTO route(title,destination_id,price,status) VALUES('${title}',${d},${price},0);SELECT LAST_INSERT_ID()`));rids.push(id);return id;}
(async()=>{try{
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning'&&m.text().includes('[Vue warn]'))warnings.push(m.text())});page.on('request',r=>{if(r.url().includes('/analysis/dashboard'))requests.push(new URL(r.url()).pathname+new URL(r.url()).search)});
 await page.goto(base+'/admin/analytics');await page.waitForURL(u=>u.pathname==='/login');check('anonymous admin page redirects to login',new URL(page.url()).pathname,'/login');
 for(const suffix of ['a','u']){const name='aui_'+Date.now()+suffix;const result=await(await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,password})})).json();if(result.code!==200)throw Error('Fixture register failed');users.push({name,id:Number(sql(`SELECT id FROM sys_user WHERE username='${name}'`))});}
 sql(`UPDATE sys_user SET role='ADMIN' WHERE id=${users[0].id}`);const did=dest('测试目的地'),empty=dest('空目的地'),r1=route(did,'零价统计路线',0),r2=route(did,'五百元统计路线',500);
 for(let i=0;i<4;i++)sql(`INSERT INTO route_booking(booking_no,route_id,user_id,travel_date,contact_name,contact_phone,status) VALUES('${marker+i}',${i===3?r2:r1},${users[1].id},'2099-01-01','UI夹具','00000000000',${i})`);
 sql(`INSERT INTO llm_call_log(user_id,scene,model,cost_ms,success) VALUES(${users[1].id},'ANALYSIS_UI_FIXTURE','no-provider',100,1),(${users[1].id},'ANALYSIS_UI_FIXTURE','no-provider',300,0)`);
 await login(users[0],'/admin/analytics');await ready();check('navigation has selected visualisation entry',await page.getByRole('link',{name:'数据与可视化',exact:true}).getAttribute('class').then(c=>c.includes('active')),true);
 check('five real chart figures',await page.locator('.analytics-chart').count(),5);check('all SVG drawn',await page.locator('.analytics-chart svg').count(),5);check('Chinese scope visible',await page.getByText('目的地筛选仅影响路线与预约；用户、模型指标为全站。含上下架，排除已删除路线与目的地。',{exact:true}).count(),1);
 check('thirty dates in initial trend',await page.locator('.analytics-chart').first().locator('circle[role="button"]').count(),30);
 await choose('统计目的地',marker+'测试目的地');check('selected actual booking count',await page.getByTestId('analysis-metrics').locator('dd').first().innerText(),'4');check('filtered real route total',await page.getByTestId('analysis-metrics').locator('dd').nth(1).innerText(),'2');
 const scatter=page.locator('figure').filter({has:page.locator('figcaption',{hasText:'路线参考价与预约量'})});check('two plotted points for two actual routes',await scatter.locator('circle[role="button"]').count(),2);await scatter.locator('circle[role="button"]').first().focus();await page.keyboard.press('Enter');check('keyboard reveals exact zero price and actual bookings',await scatter.locator('.chart-detail').innerText(),'零价统计路线：人均参考价（元） 0，预约单数 3');
 await scatter.locator('circle[role="button"]').nth(1).hover();check('hover reads second exact point',await scatter.locator('.chart-detail').innerText(),'五百元统计路线：人均参考价（元） 500，预约单数 1');check('reference price not revenue label',await scatter.locator('svg text').allTextContents().then(t=>t.includes('人均参考价（元）')),true);
 const heat=page.locator('figure').filter({has:page.locator('figcaption',{hasText:'目的地预约热度'})});check('one actual heat bar',await heat.locator('rect').count(),1);await heat.locator('rect').focus();check('keyboard reads actual heat value',await heat.locator('.chart-detail').innerText(),marker+'测试目的地：4');
 check('scatter detail table includes both names',await page.locator('.analysis-table').first().innerText().then(t=>t.includes('零价统计路线')&&t.includes('五百元统计路线')),true);
 await choose('统计窗口','近7日');check('seven daily points',await page.locator('figure').first().locator('circle[role="button"]').count(),7);await choose('统计窗口','近90日');check('ninety daily points',await page.locator('figure').first().locator('circle[role="button"]').count(),90);
 await page.locator('details summary').click();check('daily data table has ninety records',await page.locator('details .el-table__body tbody tr').count(),90);await page.locator('details summary').click();
 const before=requests.length;await choose('趋势指标','模型调用（全站）');check('trend indicator does not refetch',requests.length,before);check('model trend title explicit global',await page.locator('figure').first().locator('figcaption').innerText(),'模型调用记录趋势（全站）');
 await choose('趋势指标','新增用户（全站）');check('global users trend drawn',await page.locator('figure').first().locator('polyline').count(),1);await choose('趋势指标','预约创建');await choose('统计窗口','近30日');
 check('desktop no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'analytics-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>Number(document.querySelector('.analytics-chart svg')?.getAttribute('viewBox')?.split(' ')[2])<400);check('mobile chart coordinates reflow instead of shrinking text',await page.locator('figure').first().locator('svg').getAttribute('viewBox').then(v=>Number(v.split(' ')[2])<400),true);check('mobile axis text remains readable',await page.locator('figure').first().locator('svg text').first().evaluate(e=>parseFloat(getComputedStyle(e).fontSize)*e.getScreenCTM().a>=13),true);check('mobile no page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'analytics-mobile.png'),fullPage:true});
 await page.setViewportSize({width:320,height:800});await page.waitForFunction(()=>Number(document.querySelector('.analytics-chart svg')?.getAttribute('viewBox')?.split(' ')[2])<=300);check('320px no page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.setViewportSize({width:390,height:844});await choose('统计目的地',marker+'空目的地');check('empty scope displays zero metric',await page.getByTestId('analysis-metrics').locator('dd').first().innerText(),'0');check('empty scope graphs explicitly empty',await page.getByText('当前范围暂无数据',{exact:true}).count(),2);check('empty table message present',await page.getByText('当前范围暂无路线',{exact:true}).count(),1);check('empty scope retains four state legend labels',await page.locator('figure').nth(3).locator('.donut-legend button').count(),4);check('zero scope draws no invented donut sectors',await page.locator('figure').nth(3).locator('.donut-sector').count(),0);await page.getByRole('combobox',{name:'统计目的地',exact:true}).blur();await page.waitForFunction(()=>Array.from(document.querySelectorAll('.el-popper')).every(e=>!e.getClientRects().length||getComputedStyle(e).visibility==='hidden'||getComputedStyle(e).display==='none'));await page.screenshot({path:path.join(out,'analytics-empty-mobile.png'),fullPage:true});
 let fail=true,delay=false;
 await context.route('**/api/admin/analysis/dashboard?**',async r=>{if(fail){await r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:503,message:'验收控制的临时网络失败',data:null})});return}if(delay&&r.request().url().includes('days=7')){const actual=await r.fetch();await new Promise(resolve=>setTimeout(resolve,900));try{await r.fulfill({response:actual})}catch{}return}await r.continue();});
 await page.getByRole('button',{name:'刷新统计',exact:true}).click();await page.getByRole('alert').filter({hasText:'无法加载统计'}).waitFor();check('error replaces charts and old snapshot',[await page.locator('figure').count(),await page.getByTestId('analysis-snapshot').count()],[0,0]);check('error has retry',await page.getByRole('button',{name:'重试统计',exact:true}).count(),1);fail=false;await page.getByRole('button',{name:'重试统计',exact:true}).click();await ready();check('real retry restores data',await page.locator('figure').count(),5);
 delay=true;await page.getByRole('combobox',{name:'统计窗口',exact:true}).focus();await page.getByRole('combobox',{name:'统计窗口',exact:true}).press('ArrowDown');await page.getByRole('option',{name:'近7日',exact:true}).click();await page.getByRole('combobox',{name:'统计窗口',exact:true}).focus();await page.getByRole('combobox',{name:'统计窗口',exact:true}).press('ArrowDown');await page.getByRole('option',{name:'近90日',exact:true}).click();await ready();await page.waitForTimeout(1000);check('delayed old filter does not replace latest data',await page.locator('figure').first().locator('circle[role="button"]').count(),90);check('race finishes without canceled request error',await page.getByRole('alert').filter({hasText:'无法加载统计'}).count(),0);
 await context.unrouteAll({behavior:'wait'});await page.locator('.analysis-filters .el-select').nth(1).hover();await page.locator('.analysis-filters .el-select__clear').click();await ready();check('clear destination restores full scope',await page.getByTestId('analysis-snapshot').innerText().then(t=>t.includes('全部目的地')),true);await page.evaluate(()=>localStorage.clear());await login(users[1],'/');await page.goto(base+'/admin/analytics');await page.waitForURL(u=>u.pathname==='/');check('normal user cannot open analytics page',new URL(page.url()).pathname,'/');
 check('no Vue warnings',warnings.length,0);check('no browser exceptions',errors.length,0);phase='COMPLETED';
}catch(e){check('browser completed',e.message,'no error');phase='FAILED';process.exitCode=1}finally{
 if(browser)await browser.close();if(rids.length){const ids=rids.join(',');sql(`DELETE FROM route_booking WHERE route_id IN (${ids});DELETE FROM route WHERE id IN (${ids})`);check('owned routes removed',sql(`SELECT COUNT(*) FROM route WHERE id IN (${ids})`),'0')}if(dids.length){const ids=dids.join(',');sql(`DELETE FROM destination WHERE id IN (${ids})`);check('owned destinations removed',sql(`SELECT COUNT(*) FROM destination WHERE id IN (${ids})`),'0')}for(const u of users){sql(`DELETE FROM llm_call_log WHERE user_id=${u.id};DELETE FROM sys_user WHERE id=${u.id}`);cleanSessions(u.id);check('owned user removed '+u.id,sql(`SELECT COUNT(*) FROM sys_user WHERE id=${u.id}`),'0')}save();console.log(`${checks.filter(c=>c.passed).length}/${checks.length} passed; ${out}`);if(checks.some(c=>!c.passed))process.exitCode=1;
}})();
