// Real app/Edge/MySQL/Redis, generated accounts and catalog fixtures only, no model calls.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),{cleanSessions,cleanModelState}=require('./redis_fixture.cjs');
const base='http://127.0.0.1:5173',password='BasicDataUi123',users=[],checks=[],errors=[],marker='bui'+Date.now(),out=path.resolve(__dirname,'../../docs/dev/evidence/basic-data',new Date().toISOString().replace(/[:.]/g,'-')+'-browser');
fs.mkdirSync(out,{recursive:true});let browser,page,phase='RUNNING';
function sql(q){return execFileSync('mysql',['-u','root','-N','-B','--default-character-set=utf8mb4','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
function save(){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:'REAL_EDGE_HTTP_MYSQL_REDIS_NO_MODEL',phase,checks,errors,summary:{total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length}},null,2));}
function check(name,actual,expected){checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
async function login(user,redirect){await page.goto(base+'/login?redirect='+encodeURIComponent(redirect));await page.getByPlaceholder('user1001').fill(user.name);await page.getByPlaceholder('123456',{exact:true}).fill(password);await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL(u=>u.pathname===redirect);}
async function chooseFile(records){await page.getByLabel('选择导入JSON文件',{exact:true}).setInputFiles({name:'fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,type:'DESTINATION',records}))});}
async function clickRequest(name,endpoint){const response=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST');await page.getByRole('button',{name,exact:true}).click();return(await response).json();}
(async()=>{try{
 for(const suffix of ['a','u']){const name='bt_'+Date.now()+suffix;const r=await(await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,password})})).json();if(r.code!==200)throw Error('Fixture registration failed');users.push({name,id:Number(sql(`SELECT id FROM sys_user WHERE username='${name}'`))});}
 sql(`UPDATE sys_user SET role='ADMIN' WHERE id=${users[0].id}`);browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));await login(users[0],'/admin/users');
 await page.getByLabel('搜索用户',{exact:true}).fill(users[0].name);await page.getByRole('button',{name:'查询',exact:true}).click();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'导出筛选用户CSV',exact:true}).click();const downloaded=await dl;const csv=fs.readFileSync(await downloaded.path(),'utf8');check('actual user CSV download filename',downloaded.suggestedFilename(),'users.csv');check('CSV contains filtered fixture',csv.includes(users[0].name),true);check('CSV excludes unrelated fixture',csv.includes(users[1].name),false);check('CSV no password field',csv.toLowerCase().includes('password'),false);check('CSV has UTF8 BOM',csv.charCodeAt(0),65279);
 await page.getByRole('link',{name:'内容批量导入',exact:true}).click();await page.waitForURL(u=>u.pathname==='/admin/import');const td=page.waitForEvent('download');await page.getByRole('button',{name:'下载JSON模板',exact:true}).click();const template=JSON.parse(fs.readFileSync(await(await td).path(),'utf8'));check('template is valid bounded format',[template.version,template.type,template.records[0].status],[1,'DESTINATION',0]);
 const record={name:marker,province:'浙江省',city:'验收',longitude:120,latitude:30,coverImg:'https://example.com/fixture.jpg',status:0};await chooseFile([{...record,longitude:'120'}]);const invalid=await clickRequest('预览并校验','/admin/catalog/import/preview');check('invalid file shown',invalid.data.valid,false);check('invalid preview disables commit',await page.getByRole('button',{name:'确认导入整批',exact:true}).isDisabled(),true);check('invalid preview writes nothing',sql(`SELECT COUNT(*) FROM destination WHERE name LIKE '${marker}%'`),'0');
 await chooseFile([record,{...record,name:marker+'b'}]);const valid=await clickRequest('预览并校验','/admin/catalog/import/preview');check('valid preview shown',[valid.data.valid,valid.data.total],[true,2]);await page.getByTestId('import-preview').waitFor();check('valid preview also writes nothing',sql(`SELECT COUNT(*) FROM destination WHERE name LIKE '${marker}%'`),'0');await page.getByTestId('import-ack').click();await page.getByRole('button',{name:'确认导入整批',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();check('cancelled import confirmation writes nothing',sql(`SELECT COUNT(*) FROM destination WHERE name LIKE '${marker}%'`),'0');
 await page.locator('.el-message-box').waitFor({state:'hidden'});await page.screenshot({path:path.join(out,'import-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});check('import mobile no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'import-mobile.png'),fullPage:true});
 const imported=page.waitForResponse(r=>r.url().endsWith('/admin/catalog/import/commit'));await page.getByRole('button',{name:'确认导入整批',exact:true}).click();await page.getByRole('button',{name:'确定',exact:true}).click();const result=await(await imported).json();check('real commit succeeds',result.code,200);await page.getByTestId('import-result').waitFor();check('SQL has exactly two offline records',sql(`SELECT CONCAT(COUNT(*),':',SUM(status)) FROM destination WHERE name LIKE '${marker}%'`),'2:0');check('finished import disables repeat click',await page.getByRole('button',{name:'确认导入整批',exact:true}).isDisabled(),true);
 await page.goto(base+'/user/profile');await page.getByRole('heading',{name:'个人资料',exact:true}).waitFor();check('admin closure control hidden',await page.getByRole('button',{name:'申请注销账号',exact:true}).count(),0);
 await page.evaluate(()=>localStorage.clear());await login(users[1],'/user/profile');await page.getByRole('heading',{name:'注销账号',exact:true}).waitFor();check('closure starts disabled until acknowledged',await page.getByRole('button',{name:'申请注销账号',exact:true}).isDisabled(),true);
 await page.getByLabel('注销当前密码',{exact:true}).fill('WrongPass123');await page.getByLabel('注销确认文字',{exact:true}).fill('注销账号');await page.getByTestId('close-ack').click();await page.getByRole('button',{name:'申请注销账号',exact:true}).click();await page.getByRole('button',{name:'保留账号',exact:true}).click();check('cancelled closure keeps active user',sql(`SELECT CONCAT(deleted,':',status) FROM sys_user WHERE id=${users[1].id}`),'0:1');
 let closeResponse=page.waitForResponse(r=>r.url().endsWith('/user/account/close'));await page.getByRole('button',{name:'申请注销账号',exact:true}).click();await page.getByRole('button',{name:'确认注销',exact:true}).click();check('wrong password rejected', (await(await closeResponse).json()).code,400);check('validation error preserves page',new URL(page.url()).pathname,'/user/profile');await page.getByLabel('注销当前密码',{exact:true}).fill(password);await page.waitForFunction(()=>document.querySelectorAll('.el-message').length===0);check('closure mobile no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'closure-mobile.png'),fullPage:true,mask:[page.getByLabel('注销当前密码',{exact:true}),page.getByLabel('原密码',{exact:true}),page.getByLabel('新密码',{exact:true}),page.getByLabel('确认新密码',{exact:true})]});
 closeResponse=page.waitForResponse(r=>r.url().endsWith('/user/account/close'));await page.getByRole('button',{name:'申请注销账号',exact:true}).click();await page.getByRole('button',{name:'确认注销',exact:true}).click();check('own closure succeeds',(await(await closeResponse).json()).code,200);await page.waitForURL(u=>u.pathname==='/login');check('SQL logically closed account',sql(`SELECT CONCAT(deleted,':',status) FROM sys_user WHERE id=${users[1].id}`),'1:0');check('local auth removed',await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes('auth')).length),0);check('no browser errors',errors.length,0);phase='COMPLETED';
}catch(e){check('browser completed',e.message,'no error');phase='FAILED';process.exitCode=1;}finally{
 if(browser)await browser.close();sql(`DELETE FROM destination WHERE name LIKE '${marker}%'`);for(const user of users){cleanSessions(user.id);cleanModelState(user.id);sql(`DELETE FROM catalog_import_batch WHERE user_id=${user.id}; DELETE FROM user_preference WHERE user_id=${user.id}; DELETE FROM sys_user WHERE id=${user.id}`);check('owned fixture removed '+user.id,sql(`SELECT COUNT(*) FROM sys_user WHERE id=${user.id}`),'0');}save();console.log(`${checks.filter(c=>c.passed).length}/${checks.length} passed; ${out}`);if(checks.some(c=>!c.passed))process.exitCode=1;
}})();
