// Real Edge + live backend/MySQL. No API responses are mocked.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {cleanSessions,cleanModelState}=require('./redis_fixture.cjs');
const base='http://127.0.0.1:5173',prefix='KQUI_'+crypto.randomUUID().replaceAll('-','').slice(0,6),password='InitialUi123',label=process.argv[2]||'final';
const out=path.resolve(__dirname,'../../docs/dev/evidence/knowledge-quality',new Date().toISOString().replace(/[:.]/g,'-')+'-'+label+'-browser');
const report={mode:'REAL_EDGE_KNOWLEDGE_MAINTENANCE_NO_LLM',phase:'RUNNING',checks:[],errors:[],accounts:[],fixtures:[]};let browser;const docs=[];
fs.mkdirSync(out,{recursive:true});
function save(){report.summary={total:report.checks.length,passed:report.checks.filter(x=>x.passed).length,failed:report.checks.filter(x=>!x.passed).length};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));}
function check(name,actual,expected){report.checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
function sql(q){return execFileSync('mysql',['-u','root','--default-character-set=utf8mb4','-N','-B','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
async function api(p,body,method='POST',token){return (await fetch(base+'/api'+p,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})})).json();}
async function changed(page,action,p,method='GET'){const promise=page.waitForResponse(r=>new URL(r.url()).pathname==='/api'+p&&r.request().method()===method).then(r=>r.json());await action();return promise;}
async function pick(page,label,name){await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:label,exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name,exact:true}).click();}
async function login(page,user){await page.goto(base+'/login?redirect=/admin/ai/knowledge');await page.getByPlaceholder('user1001').fill(user.username);await page.getByPlaceholder('123456',{exact:true}).fill(password);const r=await changed(page,()=>page.getByRole('button',{name:'登 录',exact:true}).click(),'/auth/login','POST');check('real admin UI login',r.code,200);await page.waitForURL(u=>u.pathname==='/admin/ai/knowledge');await page.getByTestId('knowledge-health').waitFor();}
async function capture(page,name){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,name),fullPage:true});}
async function run(){try{
  for(const role of ['admin','reader']){const username=prefix+'_'+role;const r=await api('/auth/register',{username,password});check('real fixture register '+role,r.code,200);if(!r.data)throw Error('registration failed');const id=r.data.id;report.accounts.push({id,username,role});if(role==='admin')sql(`UPDATE sys_user SET role='ADMIN' WHERE id=${id}`);save();}
  const auth=await api('/auth/login',{username:report.accounts[0].username,password});const at=auth.data.accessToken;
  async function doc(suffix,status=1){const r=await api('/admin/ai/knowledge',{title:prefix+suffix,docType:'GUIDE',sourceId:null,status,content:'霁澜维护，真实检索资料。'},'POST',at);check('real owned doc create '+suffix,r.code,200);docs.push(r.data.id);report.fixtures.push({docId:r.data.id,title:r.data.title});save();return r.data;}
  const a=await doc('缺片'),b=await doc('停用过期',0),c=await doc('健康');sql(`DELETE FROM knowledge_chunk WHERE doc_id=${a.id}`);sql(`UPDATE knowledge_doc SET revision=revision+1 WHERE id=${b.id}`);b.revision++;
  browser=await chromium.launch({channel:'msedge',headless:true});const page=await (await browser.newContext({viewport:{width:1440,height:1000}})).newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>{report.errors.push(e.message);save();});await login(page,report.accounts[0]);
  await page.getByLabel('资料标题筛选',{exact:true}).fill(prefix);const list=await changed(page,()=>page.getByRole('button',{name:'查询',exact:true}).click(),'/admin/ai/knowledge/page');check('UI own docs filtered',list.data.total,3);await page.getByText(prefix+'缺片',{exact:true}).waitFor();check('missing chunks reason shown',await page.locator('.el-table__body-wrapper').innerText().then(t=>t.includes('分片缺失')&&t.includes('0/1片')),true);
  const health=await api('/admin/ai/knowledge/health',undefined,'GET',at);check('health count matches actual',Number(await page.getByTestId('needs-rebuild').textContent()),health.data.needsRebuild);await capture(page,'maintenance-desktop.png');
  await pick(page,'资料索引筛选','待修复索引');const bad=await changed(page,()=>page.getByRole('button',{name:'查询',exact:true}).click(),'/admin/ai/knowledge/page');check('UI selects damaged only',bad.data.records.map(x=>x.id).sort((x,y)=>x-y),[a.id,b.id].sort((x,y)=>x-y));await page.locator('.el-table__body-wrapper tr').filter({hasText:prefix+'缺片'}).locator('.el-checkbox').click();await page.locator('.el-table__body-wrapper tr').filter({hasText:prefix+'停用过期'}).locator('.el-checkbox').click();await page.getByText('已选2篇（每次最多10篇）',{exact:true}).waitFor();
  // Simulate another editor while the first window keeps its old selected revision.
  sql(`UPDATE knowledge_doc SET revision=revision+1 WHERE id=${b.id}`);b.revision++;
  await page.getByRole('button',{name:'修复选中索引',exact:true}).click();const dialog=page.getByRole('dialog',{name:'修复资料索引'});await dialog.waitFor();check('confirmation mentions historical references',await dialog.innerText().then(t=>t.includes('旧历史引用可能失效')),true);const repaired=await changed(page,()=>dialog.getByRole('button',{name:'确认修复',exact:true}).click(),'/admin/ai/knowledge/repair','POST');
  check('UI partial repair actual codes',repaired.data.results.map(x=>[x.id,x.code]).sort((x,y)=>x[0]-y[0]),[[a.id,200],[b.id,409]].sort((x,y)=>x[0]-y[0]));await page.getByTestId('repair-results').getByText('已修复1篇，保持就绪0篇，失败1篇。',{exact:true}).waitFor();check('partial failure visible',await page.getByTestId('repair-results').innerText().then(t=>t.includes('409')&&t.includes('资料已被更新')),true);
  await page.getByText('已选0篇（每次最多10篇）',{exact:true}).waitFor();await page.locator('.el-table__body-wrapper tr').filter({hasText:prefix+'停用过期'}).locator('.el-checkbox').click();await page.getByRole('button',{name:'修复选中索引',exact:true}).click();const fixed=await changed(page,()=>page.getByRole('dialog',{name:'修复资料索引'}).getByRole('button',{name:'确认修复',exact:true}).click(),'/admin/ai/knowledge/repair','POST');check('fresh revision repair succeeds',fixed.data.succeeded,1);await page.getByTestId('repair-results').getByText('已修复1篇，保持就绪0篇，失败0篇。',{exact:true}).waitFor();check('SQL repaired metadata',sql(`SELECT indexed_revision=revision FROM knowledge_doc WHERE id=${b.id}`),'1');check('disabled doc remains disabled',sql(`SELECT status FROM knowledge_doc WHERE id=${b.id}`),'0');
  await pick(page,'资料索引筛选','索引就绪');await changed(page,()=>page.getByRole('button',{name:'查询',exact:true}).click(),'/admin/ai/knowledge/page');await page.getByText(prefix+'健康',{exact:true}).waitFor();const ids=sql(`SELECT GROUP_CONCAT(id ORDER BY id) FROM knowledge_chunk WHERE doc_id=${c.id}`);await page.locator('.el-table__body-wrapper tr').filter({hasText:prefix+'健康'}).locator('.el-checkbox').click();await page.getByRole('button',{name:'修复选中索引',exact:true}).click();const unchanged=await changed(page,()=>page.getByRole('dialog',{name:'修复资料索引'}).getByRole('button',{name:'确认修复',exact:true}).click(),'/admin/ai/knowledge/repair','POST');check('healthy selected unchanged',unchanged.data.unchanged,1);await page.getByTestId('repair-results').getByText('已修复0篇，保持就绪1篇，失败0篇。',{exact:true}).waitFor();check('healthy history chunk IDs unchanged',sql(`SELECT GROUP_CONCAT(id ORDER BY id) FROM knowledge_chunk WHERE doc_id=${c.id}`),ids);
  await pick(page,'资料来源筛选','待关联来源');const noSource=await changed(page,()=>page.getByRole('button',{name:'查询',exact:true}).click(),'/admin/ai/knowledge/page');check('guide is not missing source',noSource.data.total,0);await pick(page,'资料来源筛选','来源可用');await changed(page,()=>page.getByRole('button',{name:'查询',exact:true}).click(),'/admin/ai/knowledge/page');await page.getByText(prefix+'健康',{exact:true}).waitFor();
  for(const width of [375,768]){await page.setViewportSize({width,height:900});await page.getByTestId('knowledge-health').waitFor();check('responsive no page overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}await capture(page,'maintenance-mobile.png');
  const reader=(await api('/auth/login',{username:report.accounts[1].username,password})).data.accessToken;const denied=await api('/admin/ai/knowledge/health',undefined,'GET',reader);check('reader admin health denied',denied.code,403);
  check('no page errors',report.errors.length,0);
}catch(e){check('browser run completed',e.message,'no error');if(browser){const pages=browser.contexts().flatMap(c=>c.pages());if(pages[0])await capture(pages[0],'failure.png').catch(()=>{});}}
finally{for(const id of docs){sql(`DELETE FROM knowledge_chunk WHERE doc_id=${id}`);sql(`DELETE FROM knowledge_doc WHERE id=${id}`);}for(const u of report.accounts){sql(`DELETE FROM sys_user WHERE id=${u.id}`);cleanSessions(u.id);cleanModelState(u.id);}check('owned doc cleanup',Number(sql(`SELECT COUNT(*) FROM knowledge_doc WHERE title LIKE '${prefix}%'`)),0);report.phase='COMPLETE';save();if(browser)await browser.close();}
console.log(`${report.summary.passed}/${report.summary.total}; ${out}`);process.exitCode=Number(report.summary.failed>0);}
run();
