// Real Edge. One response-loss injection first sends to the real server, then drops only its response.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process'),{cleanSessions,cleanModelState}=require('./redis_fixture.cjs');
const base='http://127.0.0.1:5173',prefix='KSUI_'+crypto.randomUUID().replaceAll('-','').slice(0,8),password='InitialUi123',label=process.argv[2]||'final';
const out=path.resolve(__dirname,'../../docs/dev/evidence/knowledge-sessions',new Date().toISOString().replace(/[:.]/g,'-')+'-'+label+'-browser');
const report={mode:'REAL_EDGE_PRIVATE_LOCAL_HISTORY_RESPONSE_LOSS_NO_LLM',label,phase:'RUNNING',checks:[],errors:[],accounts:[],fixtures:[]};let browser;const docs=[];
fs.mkdirSync(out,{recursive:true});
function save(){report.summary={total:report.checks.length,passed:report.checks.filter(x=>x.passed).length,failed:report.checks.filter(x=>!x.passed).length};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));}
function check(name,actual,expected){report.checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
function sql(q){return execFileSync('mysql',['-u','root','--default-character-set=utf8mb4','-N','-B','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
async function api(p,body,method='POST',token){return (await fetch(base+'/api'+p,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})})).json();}
function watch(page,name){page.setDefaultTimeout(15000);page.on('pageerror',e=>{report.errors.push({page:name,message:e.message});save();});}
async function changed(page,action,end,method='POST'){const p=page.waitForResponse(r=>new URL(r.url()).pathname==='/api'+end&&r.request().method()===method).then(r=>r.json());await action();return p;}
async function login(page,user){await page.goto(base+'/login?redirect=/ai/chat');await page.getByPlaceholder('user1001').fill(user.username);await page.getByPlaceholder('123456',{exact:true}).fill(password);const data=await changed(page,()=>page.getByRole('button',{name:'登 录',exact:true}).click(),'/auth/login');check('actual '+user.role+' UI login',data.code,200);await page.waitForURL(u=>u.pathname==='/ai/chat');await page.getByRole('heading',{name:'资料检索会话',exact:true}).waitFor();return page.evaluate(()=>localStorage.getItem('trip_token'));}
async function run(){try{
  for(const role of ['READER','OTHER','ADMIN']){const username=prefix+'_'+role.toLowerCase();const registered=await api('/auth/register',{username,password,nickname:'Session '+role});check('registered fixture '+role,registered.code,200);if(registered.code!==200)throw Error('register failed');const id=Number(sql(`SELECT id FROM sys_user WHERE username='${username}'`));report.accounts.push({id,username,role});save();if(role==='ADMIN')sql(`UPDATE sys_user SET role='ADMIN' WHERE id=${id}`);}
  const auth=await api('/auth/login',{username:report.accounts[2].username,password});const at=auth.data.accessToken;
  browser=await chromium.launch({channel:'msedge',headless:true});const page=await (await browser.newContext({viewport:{width:1440,height:1000}})).newPage(),other=await (await browser.newContext({viewport:{width:1360,height:900}})).newPage();watch(page,'reader');watch(other,'other reader');
  const ut=await login(page,report.accounts[0]);await login(other,report.accounts[1]);
  const docInput={title:prefix+'原文旧标题',docType:'GUIDE',sourceId:null,status:1,content:'霁澜回看，旧私密摘录。<img src=x onerror="window.sessionXss=1">\n'+('甲乙丙丁戊己庚辛壬癸'.repeat(100))};
  let doc=(await api('/admin/ai/knowledge',docInput,'POST',at)).data;if(!doc)throw Error('knowledge fixture failed');docs.push(doc.id);report.fixtures.push({docId:doc.id,title:doc.title});save();
  const created=await changed(page,()=>page.getByRole('button',{name:'新建资料会话',exact:true}).click(),'/ai/chat/session');check('UI creates private session',created.code,200);let session=created.data;report.fixtures.push({sessionId:session.id,userId:report.accounts[0].id});save();await page.waitForURL(u=>u.searchParams.get('sessionId')===String(session.id));await page.getByTestId('selected-session-title').getByText('新资料会话',{exact:true}).waitFor();
  await page.getByLabel('会话检索问题',{exact:true}).fill('霁澜回看');const found=await changed(page,()=>page.getByRole('button',{name:'检索并保存',exact:true}).click(),'/ai/chat/search');check('UI atomic local turn',[found.code,found.data.replayed,found.data.messages.length],[200,false,2]);session=found.data.session;await page.getByTestId('history-reference').first().waitFor();check('first turn title auto',[await page.getByTestId('selected-session-title').textContent(),session.messageCount],['霁澜回看',2]);
  check('literal HTML text safe',await page.getByTestId('history-reference').first().locator('pre').textContent().then(t=>t.includes('<img src=x')),true);check('no injected history image',await page.locator('.messages img').count(),0);check('no script executed',await page.evaluate(()=>window.sessionXss===undefined),true);await page.screenshot({path:path.join(out,'session-desktop.png'),fullPage:true});
  await page.getByRole('link',{name:'查看完整资料',exact:true}).first().click();await page.getByTestId('knowledge-document').waitFor();check('real source navigation',new URL(page.url()).pathname,'/knowledge/'+doc.id);await page.goBack();await page.getByTestId('selected-session-title').waitFor();
  for(let n=0;n<10;n++){const r=await api('/ai/chat/search',{sessionId:session.id,query:'霁澜回看',topK:1,requestId:crypto.randomUUID()},'POST',ut);check('real appended history '+n,r.code,200);}
  await page.getByRole('button',{name:'刷新会话',exact:true}).click();await page.getByRole('button',{name:'加载更早记录',exact:true}).waitFor();check('latest page bounded',await page.locator('.history-message').count(),20);await page.getByRole('button',{name:'加载更早记录',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.history-message').length===22);check('older cursor adds without duplicates',await page.locator('.history-message').evaluateAll(elements=>new Set(elements.map(e=>e.dataset.testid)).size),22);check('older end no extra button',await page.getByRole('button',{name:'加载更早记录',exact:true}).count(),0);
  const hidden=await api('/admin/ai/knowledge/'+doc.id+'/status',{status:0,expectedRevision:doc.revision},'PUT',at);doc=hidden.data;await page.getByRole('button',{name:'刷新会话',exact:true}).click();await page.getByText('部分历史引用已更新或不再公开，已隐藏旧片段，请重新检索',{exact:true}).first().waitFor();check('hidden reference body absent',await page.locator('.messages').innerText().then(t=>t.includes('旧私密摘录')||t.includes(docInput.title)),false);check('hidden reference links absent',await page.locator(`.messages a[href='/knowledge/${doc.id}']`).count(),0);await page.screenshot({path:path.join(out,'history-source-hidden.png'),fullPage:true});
  doc=(await api('/admin/ai/knowledge/'+doc.id+'/status',{status:1,expectedRevision:doc.revision},'PUT',at)).data;await page.getByRole('button',{name:'刷新会话',exact:true}).click();await page.getByTestId('history-reference').first().waitFor();check('restored source revalidated',await page.locator('.messages').innerText().then(t=>t.includes('旧私密摘录')),true);
  doc=(await api('/admin/ai/knowledge/'+doc.id,{...docInput,title:prefix+'当前原文',content:'晴岚回看，新的资料正文。',expectedRevision:doc.revision},'PUT',at)).data;await page.getByRole('button',{name:'刷新会话',exact:true}).click();await page.getByText('部分历史引用已更新或不再公开，已隐藏旧片段，请重新检索',{exact:true}).first().waitFor();check('edited source old history hidden',await page.locator('.messages').innerText().then(t=>t.includes('旧私密摘录')),false);
  await page.getByLabel('会话检索问题',{exact:true}).fill('晴岚回看');const fresh=await changed(page,()=>page.getByRole('button',{name:'检索并保存',exact:true}).click(),'/ai/chat/search');session=fresh.data.session;check('new result current original',fresh.data.messages[1].result.references[0].excerpt,'晴岚回看，新的资料正文。');await page.getByTestId('history-reference').first().waitFor();
  // Real second editor creates a CAS conflict; current user's draft must survive.
  await page.getByRole('button',{name:'重命名',exact:true}).click();let dialog=page.getByRole('dialog',{name:'重命名资料会话'});await dialog.getByLabel('新的会话标题').fill(prefix+'我的记录');const concurrent=await api('/ai/chat/session/'+session.id,{title:'另一个窗口的名称',expectedRevision:session.revision},'PUT',ut);check('real concurrent rename',concurrent.code,200);
  const conflict=await changed(page,()=>dialog.getByRole('button',{name:'保存标题',exact:true}).click(),'/ai/chat/session/'+session.id,'PUT');check('UI stale rename conflict',conflict.code,409);await dialog.getByText('会话已变化，标题输入已保留。请复制需要的内容，关闭后刷新会话再修改。',{exact:true}).waitFor();check('rename draft retained',await dialog.getByLabel('新的会话标题').inputValue(),prefix+'我的记录');await dialog.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'刷新会话',exact:true}).click();await page.getByTestId('selected-session-title').getByText('另一个窗口的名称',{exact:true}).waitFor();
  await page.getByRole('button',{name:'重命名',exact:true}).click();dialog=page.getByRole('dialog',{name:'重命名资料会话'});await dialog.getByLabel('新的会话标题').fill(prefix+'我的记录');const renamed=await changed(page,()=>dialog.getByRole('button',{name:'保存标题',exact:true}).click(),'/ai/chat/session/'+session.id,'PUT');check('fresh rename succeeds',renamed.code,200);await dialog.waitFor({state:'hidden'});session=renamed.data;
  const second=await changed(page,()=>page.getByRole('button',{name:'新建资料会话',exact:true}).click(),'/ai/chat/session');report.fixtures.push({sessionId:second.data.id,userId:report.accounts[0].id});save();await page.waitForURL(u=>u.searchParams.get('sessionId')===String(second.data.id));await page.getByTestId('selected-session-title').getByText('新资料会话',{exact:true}).waitFor();check('new session starts empty',await page.locator('.history-message').count(),0);await page.getByTestId('session-'+session.id).click();await page.waitForURL(u=>u.searchParams.get('sessionId')===String(session.id));await page.getByTestId('selected-session-title').getByText(prefix+'我的记录',{exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('.history-message').length===20);check('switch restores history',await page.locator('.history-message').count(),20);
  await other.goto(base+'/ai/chat?sessionId='+session.id);await other.getByText('资料会话不存在或已删除',{exact:true}).first().waitFor();check('other account cannot render history',await other.locator('.history-message').count(),0);check('other account cannot render private title',await other.getByTestId('selected-session-title').count(),0);
  // Execute the real request successfully, then intentionally lose only its response.
  let lost;await page.route('**/api/ai/chat/search',async route=>{const response=await route.fetch();const data=await response.json();lost={request:route.request().postDataJSON(),body:data};await route.abort('failed');},{times:1});
  await page.getByLabel('会话检索问题',{exact:true}).fill('晴岚回看');await page.getByRole('button',{name:'检索并保存',exact:true}).click();await page.getByRole('button',{name:'重试这次检索',exact:true}).waitFor();check('lost response actually committed',lost.body.code,200);check('lost turn persisted twice-role only',sql(`SELECT COUNT(*) FROM llm_chat_message WHERE session_id=${session.id} AND request_id='${lost.request.requestId}'`),'2');
  await page.getByLabel('会话检索问题',{exact:true}).fill('待编辑的新问题');await page.getByRole('button',{name:'刷新会话',exact:true}).click();await page.getByRole('button',{name:'重试这次检索',exact:true}).waitFor();check('refresh retains pending draft',await page.getByLabel('会话检索问题',{exact:true}).inputValue(),'待编辑的新问题');
  const retried=await changed(page,()=>page.getByRole('button',{name:'重试这次检索',exact:true}).click(),'/ai/chat/search');check('same request recovered without duplicate',[retried.code,retried.data.replayed,retried.data.requestId],[200,true,lost.request.requestId]);check('same committed message IDs',retried.data.messages.map(m=>m.id),lost.body.data.messages.map(m=>m.id));check('retry does not append',sql(`SELECT COUNT(*) FROM llm_chat_message WHERE session_id=${session.id} AND request_id='${lost.request.requestId}'`),'2');report.responseLoss={requestId:lost.request.requestId,actualServerCode:lost.body.code,replayCode:retried.code,replayed:true};save();
  await page.setViewportSize({width:375,height:812});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));check('375px no page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'session-mobile.png'),fullPage:true});await page.setViewportSize({width:768,height:1000});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));check('768px no page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.getByLabel('会话检索问题',{exact:true}).fill('土星雷暴天气');const nohit=await changed(page,()=>page.getByRole('button',{name:'检索并保存',exact:true}).click(),'/ai/chat/search');check('UI no-match is not generated answer',[nohit.data.messages[1].result.matchedAtSearch,nohit.data.messages[1].result.references],[false,[]]);
  const deletion=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/ai/chat/session/'+session.id&&r.request().method()==='DELETE').then(r=>r.json());await page.getByRole('button',{name:'删除会话',exact:true}).click();await page.getByRole('dialog',{name:'删除资料会话'}).getByRole('button',{name:'确定',exact:true}).click();check('UI deletes session and messages',(await deletion).code,200);await page.waitForURL(u=>u.pathname==='/ai/chat'&&!u.searchParams.has('sessionId'));check('delete clears private view',await page.locator('.history-message').count(),0);check('delete purges messages SQL',sql(`SELECT COUNT(*) FROM llm_chat_message WHERE session_id=${session.id}`),'0');check('no uncaught browser errors',report.errors.length,0);
}catch(e){check('browser run completed',e.message.replaceAll(password,'<redacted>'),'no error');}finally{
  if(browser)await browser.close();for(const id of docs)sql(`DELETE FROM knowledge_doc WHERE id=${id}`);
  for(const account of report.accounts){sql(`DELETE FROM llm_chat_message WHERE session_id IN (SELECT id FROM llm_chat_session WHERE user_id=${account.id}); DELETE FROM llm_chat_session WHERE user_id=${account.id}`);cleanSessions(account.id);cleanModelState(account.id);sql(`DELETE FROM llm_call_log WHERE user_id=${account.id}; DELETE FROM user_preference WHERE user_id=${account.id}; DELETE FROM sys_user WHERE id=${account.id}`);check('owned account/session cleanup '+account.role,[sql(`SELECT COUNT(*) FROM sys_user WHERE id=${account.id}`),sql(`SELECT COUNT(*) FROM llm_chat_session WHERE user_id=${account.id}`)],['0','0']);}
  check('owned knowledge cleanup',docs.reduce((sum,id)=>sum+Number(sql(`SELECT COUNT(*) FROM knowledge_doc WHERE id=${id}`)),0),0);report.phase='COMPLETE';save();
}console.log(`${report.summary.passed}/${report.summary.total} passed; ${out}`);process.exitCode=report.summary.failed?1:0;}
run();
