// Real Edge and live HTTP/MySQL; no intercepted or mocked responses.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {cleanSessions,cleanModelState}=require('./redis_fixture.cjs');
const base='http://127.0.0.1:5173',prefix='KSUI_'+crypto.randomUUID().replaceAll('-','').slice(0,6),password='InitialUi123',label=process.argv[2]||'final';
const out=path.resolve(__dirname,'../../docs/dev/evidence/knowledge-sources',new Date().toISOString().replace(/[:.]/g,'-')+'-'+label+'-browser');
const report={mode:'REAL_EDGE_KNOWLEDGE_SOURCE_MAINTENANCE_NO_LLM',phase:'RUNNING',checks:[],errors:[],accounts:[],fixtures:[]};let browser;const docs=[],dests=[],routes=[];
fs.mkdirSync(out,{recursive:true});
function save(){report.summary={total:report.checks.length,passed:report.checks.filter(x=>x.passed).length,failed:report.checks.filter(x=>!x.passed).length};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));}
function check(name,actual,expected){report.checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
function sql(q){return execFileSync('mysql',['-u','root','--default-character-set=utf8mb4','-N','-B','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
async function api(p,body,method='POST',token){return (await fetch(base+'/api'+p,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})})).json();}
async function changed(page,action,p,method='GET'){const promise=page.waitForResponse(r=>new URL(r.url()).pathname==='/api'+p&&r.request().method()===method).then(r=>r.json());promise.catch(()=>{});await action();return promise;}
async function pick(page,label,name){await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:label,exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name,exact:true}).click();}
async function capture(page,name){await page.screenshot({path:path.join(out,name),fullPage:true});}
async function run(){try{
  for(const role of ['admin','reader']){const username=prefix+'_'+role;const r=await api('/auth/register',{username,password});check('fixture register '+role,r.code,200);if(!r.data)throw Error('registration failed');const id=r.data.id;report.accounts.push({id,username,role});if(role==='admin')sql(`UPDATE sys_user SET role='ADMIN' WHERE id=${id}`);save();}
  const at=(await api('/auth/login',{username:report.accounts[0].username,password})).data.accessToken;
  function dest(name,status=1){sql(`INSERT INTO destination(name,province,longitude,latitude,cover_img,status) VALUES ('${prefix}${name}','页面夹具',100,25,'/fixture.png',${status})`);const id=Number(sql(`SELECT id FROM destination WHERE name='${prefix}${name}'`));dests.push(id);report.fixtures.push({destinationId:id,name:prefix+name});save();return id;}
  const pub=dest('公开'),hidden=dest('隐藏',0);for(let i=0;i<22;i++)dest('分页'+i);
  sql(`INSERT INTO route(title,destination_id,cover_img,days,price,status,create_by) VALUES ('${prefix}父级隐藏路线',${hidden},'/fixture.png',2,100,1,${report.accounts[0].id})`);const route=Number(sql(`SELECT id FROM route WHERE title='${prefix}父级隐藏路线'`));routes.push(route);report.fixtures.push({routeId:route});save();
  async function doc(suffix,status){const r=await api('/admin/ai/knowledge',{title:prefix+suffix,docType:'GUIDE',sourceId:null,status,content:'知源页面实测，正文不变。'},'POST',at);check('real doc create '+suffix,r.code,200);docs.push(r.data.id);report.fixtures.push({docId:r.data.id,title:r.data.title});save();return r.data;}
  const legacy=await doc('旧资料',1),draft=await doc('草稿',0);sql(`UPDATE knowledge_doc SET doc_type='DESTINATION' WHERE id=${legacy.id}`);
  const original=sql(`SELECT GROUP_CONCAT(id ORDER BY id) FROM knowledge_chunk WHERE doc_id=${legacy.id}`);
  browser=await chromium.launch({channel:'msedge',headless:true});const page=await (await browser.newContext({viewport:{width:1440,height:1000}})).newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>{report.errors.push(e.message);save();});
  await page.goto(base+'/login?redirect=/admin/ai/knowledge');await page.getByPlaceholder('user1001').fill(report.accounts[0].username);await page.getByPlaceholder('123456',{exact:true}).fill(password);check('real UI login',(await changed(page,()=>page.getByRole('button',{name:'登 录',exact:true}).click(),'/auth/login','POST')).code,200);await page.waitForURL(u=>u.pathname==='/admin/ai/knowledge');await page.getByTestId('knowledge-health').waitFor();
  async function query(){await page.getByLabel('资料标题筛选',{exact:true}).fill(prefix);await changed(page,()=>page.getByRole('button',{name:'查询',exact:true}).click(),'/admin/ai/knowledge/page');await page.getByText(prefix+'旧资料',{exact:true}).waitFor();}
  async function open(title){await page.locator('.el-table__body-wrapper tr').filter({hasText:title}).getByRole('button',{name:'调整来源',exact:true}).click();const dialog=page.getByRole('dialog',{name:'调整资料来源',exact:true});await dialog.waitFor();return dialog;}
  async function submit(id){await page.getByRole('dialog',{name:'调整资料来源',exact:true}).getByRole('button',{name:'保存来源',exact:true}).click();const confirm=page.getByRole('dialog',{name:'确认调整来源',exact:true});await confirm.waitFor();check('explicit independent publishing warning',await confirm.innerText().then(t=>t.includes('解除目录公开状态的限制')),true);return changed(page,()=>confirm.getByRole('button',{name:'确定',exact:true}).click(),`/admin/ai/knowledge/${id}/source`,'PUT');}
  async function searchSources(text){const input=page.getByRole('textbox',{name:'来源名称筛选',exact:true});await input.waitFor();await page.getByRole('button',{name:'查询来源',exact:true}).waitFor();await input.fill(text);return changed(page,()=>page.getByRole('button',{name:'查询来源',exact:true}).click(),'/admin/ai/knowledge/sources');}
  await query();let dialog=await open(prefix+'旧资料');let list=await searchSources(prefix);check('source search actual total',list.data.total,24);await page.getByRole('combobox',{name:'关联资料来源',exact:true}).press('Escape');const next=await changed(page,()=>dialog.getByRole('button',{name:'下一页来源',exact:true}).click(),'/admin/ai/knowledge/sources');check('source page beyond first 20',next.data.current,2);
  await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'关联资料来源',exact:true})}).locator('.el-select__wrapper').click();const hiddenOption=page.getByRole('option',{name:`${prefix}隐藏 · ID ${hidden} · 未公开`,exact:true});check('enabled doc hidden option disabled',await hiddenOption.getAttribute('aria-disabled'),'true');await page.getByRole('option',{name:`${prefix}公开 · ID ${pub} · 已公开`,exact:true}).click();await page.getByRole('combobox',{name:'关联资料来源',exact:true}).press('Escape');await page.getByRole('listbox').waitFor({state:'hidden'});await capture(page,'source-desktop.png');
  const linked=await submit(legacy.id);check('legacy linked through UI',linked.code,200);await dialog.waitFor({state:'hidden'});check('UI source update keeps chunk IDs',sql(`SELECT GROUP_CONCAT(id ORDER BY id) FROM knowledge_chunk WHERE doc_id=${legacy.id}`),original);
  await query();dialog=await open(prefix+'旧资料');await dialog.getByText(`${prefix}公开 · ID ${pub} · 已公开`,{exact:true}).waitFor();check('selected source outside first page resolves',await dialog.innerText().then(t=>t.includes(prefix+'公开')&&!t.includes('原关联ID')),true);
  const latest=(await api('/admin/ai/knowledge/'+legacy.id,undefined,'GET',at)).data;check('real competing editor mutation',(await api('/admin/ai/knowledge/'+legacy.id+'/status',{status:1,expectedRevision:latest.revision},'PUT',at)).code,200);
  await pick(page,'来源类型','独立攻略');const conflict=await submit(legacy.id);check('stale UI source rejected',conflict.code,409);await dialog.getByText('资料版本已变化，选择已保留。请关闭并刷新列表后重新打开。',{exact:true}).waitFor();check('conflict selection retained',await dialog.innerText().then(t=>t.includes('独立攻略')),true);await dialog.getByRole('button',{name:'取消',exact:true}).click();await query();
  dialog=await open(prefix+'草稿');await pick(page,'来源类型','路线');await searchSources(prefix+'父级隐藏路线');await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'关联资料来源',exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:`${prefix}父级隐藏路线 · ID ${route} · ${prefix}隐藏 · 目的地未公开`,exact:true}).click();check('draft UI hidden route save',(await submit(draft.id)).code,200);await dialog.waitFor({state:'hidden'});check('draft remains disabled in SQL',sql(`SELECT status FROM knowledge_doc WHERE id=${draft.id}`),'0');
  await query();await page.locator('.el-table__body-wrapper tr').filter({hasText:prefix+'草稿'}).getByRole('button',{name:'编辑',exact:true}).click();const edit=page.getByRole('dialog',{name:'编辑资料',exact:true});await edit.waitFor();await edit.getByText(`${prefix}父级隐藏路线 · ID ${route} · ${prefix}隐藏 · 目的地未公开`,{exact:true}).waitFor();check('full editor reuses unpublished picker',await edit.innerText().then(t=>t.includes('目的地未公开')),true);await edit.getByRole('button',{name:'取消',exact:true}).click();
  dialog=await open(prefix+'旧资料');await searchSources(prefix+'公开');await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'关联资料来源',exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:`${prefix}公开 · ID ${pub} · 已公开`,exact:true}).click();sql(`UPDATE destination SET status=0 WHERE id=${pub}`);const unavailable=await submit(legacy.id);check('source hidden after selection rejected',unavailable.code,400);await dialog.getByText('关联内容不存在或未公开，请先恢复内容或将资料停用',{exact:true}).waitFor();sql(`UPDATE destination SET status=1 WHERE id=${pub}`);
  await page.getByRole('dialog',{name:'确认调整来源',exact:true}).waitFor({state:'hidden'});for(const width of [375,768]){await page.setViewportSize({width,height:900});check('source dialog no page overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await capture(page,`source-mobile-${width}.png`);}
  const final=await submit(legacy.id);check('retry valid unchanged selection',final.data.outcome,'UNCHANGED');await dialog.waitFor({state:'hidden'});
  const reader=(await api('/auth/login',{username:report.accounts[1].username,password})).data.accessToken;check('reader source catalog denied',(await api('/admin/ai/knowledge/sources?docType=DESTINATION',undefined,'GET',reader)).code,403);check('no page errors',report.errors.length,0);
}catch(e){check('browser run completed',e.message,'no error');if(browser){const page=browser.contexts().flatMap(c=>c.pages())[0];if(page)await capture(page,'failure.png').catch(()=>{});}}
finally{for(const id of docs){sql(`DELETE FROM knowledge_chunk WHERE doc_id=${id}`);sql(`DELETE FROM knowledge_doc WHERE id=${id}`);}for(const id of routes)sql(`DELETE FROM route WHERE id=${id}`);for(const id of dests)sql(`DELETE FROM destination WHERE id=${id}`);for(const u of report.accounts){sql(`DELETE FROM sys_user WHERE id=${u.id}`);cleanSessions(u.id);cleanModelState(u.id);}for(const [table,col] of [['knowledge_doc','title'],['destination','name'],['route','title']])check('owned cleanup '+table,Number(sql(`SELECT COUNT(*) FROM ${table} WHERE ${col} LIKE '${prefix}%'`)),0);report.phase='COMPLETE';save();if(browser)await browser.close();}
console.log(`${report.summary.passed}/${report.summary.total}; ${out}`);process.exitCode=Number(report.summary.failed>0);}
run();
