// Real Edge/app/catalog/SQL/Redis. Only AI SSE UI fixtures are intercepted; no real model calls.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const {cleanSessions,cleanModelState}=require('./redis_fixture.cjs');
const base='http://127.0.0.1:5173',password='MotionUi123',users=[],checks=[],errors=[],warnings=[],modelRequests=[];
const out=path.resolve(__dirname,'../../docs/dev/evidence/frontend-motion',new Date().toISOString().replace(/[:.]/g,'-')+'-browser');
fs.mkdirSync(out,{recursive:true});let browser,context,page,phase='RUNNING';
function sql(q){return execFileSync('mysql',['-u','root','-N','-B','--default-character-set=utf8mb4','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
function save(){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:'REAL_EDGE_APP_CATALOG_MYSQL_REDIS_WITH_SSE_UI_FIXTURES',phase,checks,errors,warnings,modelRequests,summary:{total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length}},null,2));}
function check(name,actual,expected){checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
async function settled(){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForFunction(()=>document.getAnimations().filter(a=>a.effect?.target?.closest?.('#app')).every(a=>a.playState!=='running'||a.effect.getTiming().iterations===Infinity));}
async function homeReady(){await page.locator('#home-title').waitFor();await page.locator('.home-page .route-card').first().waitFor();await settled();await page.waitForFunction(()=>getComputedStyle(document.querySelector('#home-title')).opacity==='1'&&getComputedStyle(document.querySelector('.user-layout__main')).opacity==='1');}
async function login(user,redirect){await page.goto(base+'/login?redirect='+encodeURIComponent(redirect));await page.getByPlaceholder('user1001').fill(user.name);await page.getByPlaceholder('123456',{exact:true}).fill(password);await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL(u=>u.pathname===redirect);}
async function media(reducedMotion){await page.emulateMedia({reducedMotion});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
function instrument(){
 window.__motionRecords=[];
 const original=Element.prototype.animate;
 Element.prototype.animate=function(frames,options){
  const animation=original.call(this,frames,options),r={node:this,duration:options.duration,delay:options.delay||0,frames,state:'running'};
  window.__motionRecords.push(r);animation.finished.then(()=>r.state='finished',()=>r.state='cancelled');return animation;
 };
}
async function prepareGeneration(){await page.getByLabel('API基础地址',{exact:true}).fill('http://127.0.0.1:11439/v1');await page.getByLabel('模型名称',{exact:true}).fill('motion-ui-fixture');await page.getByLabel('AI旅行需求',{exact:true}).fill('杭州一天轻松散步，动画页面测试');}
(async()=>{try{
 browser=await chromium.launch({channel:'msedge',headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(instrument);page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning'&&/directive|Vue warn|transition/i.test(m.text()))warnings.push(m.text());});
 await context.route('**/api/ai/planner/test',r=>{modelRequests.push('unexpected test');return r.abort();});await context.route('**/api/ai/planner/generate',r=>{modelRequests.push('unexpected ordinary generate');return r.abort();});
 await page.goto(base);await page.locator('#home-title').waitFor();await settled();
 const initial=await page.evaluate(()=>window.__motionRecords.map(r=>({duration:r.duration,delay:r.delay,frames:r.frames,tag:r.node.tagName})));
 check('actual page entry and hero animation observed',initial.some(r=>r.duration===220)&&initial.filter(r=>r.duration===280).length>=5,true);
 check('all actual imperative durations bounded',initial.every(r=>r.duration<=280&&r.delay<=175),true);check('actual hero stagger uses 35ms steps',[...new Set(initial.filter(r=>r.duration===280).map(r=>r.delay))].sort((a,b)=>a-b).slice(0,4),[0,35,70,105]);
 check('no perpetual decoration animation',await page.locator('.hero').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.effect.getTiming().iterations===Infinity).length),0);
 const cta=page.getByRole('button',{name:'开始规划',exact:true});await cta.hover();await settled();check('primary button soft hover',await cta.evaluate(e=>Math.round(new DOMMatrix(getComputedStyle(e).transform).m42)),-1);await page.mouse.down();await settled();check('primary button pressed feedback',await cta.evaluate(e=>Math.round(new DOMMatrix(getComputedStyle(e).transform).m42)),1);await page.mouse.move(0,0);await page.mouse.up();
 await page.locator('.route-card').first().waitFor();await page.locator('.route-card').first().scrollIntoViewIfNeeded();await settled();const card=page.locator('.route-card').first();
 await card.hover();await page.waitForFunction(()=>{const e=document.querySelector('.route-card');return e?.matches(':hover')&&Math.round(new DOMMatrix(getComputedStyle(e).transform).m42)===-3});await settled();check('card hover moves three pixels',await card.evaluate(e=>Math.round(new DOMMatrix(getComputedStyle(e).transform).m42)),-3);
 await page.mouse.move(0,0);await card.focus();await settled();check('card keyboard focus also moves',await card.evaluate(e=>Math.round(new DOMMatrix(getComputedStyle(e).transform).m42)),-3);
 await page.keyboard.press('Enter');await page.waitForURL(u=>u.pathname.startsWith('/route/'));await page.locator('.route-detail h1').waitFor();await settled();check('keyboard card opens live route',await page.locator('.route-detail h1').innerText().then(t=>t.length>0),true);
 await page.locator('nav').getByRole('link',{name:'路线',exact:true}).click();await page.waitForURL(u=>u.pathname==='/routes');await page.locator('.route-card').first().waitFor();await settled();
 check('selected navigation underline fully visible',await page.locator('nav').getByRole('link',{name:'路线',exact:true}).evaluate(e=>getComputedStyle(e,'::after').transform),'matrix(1, 0, 0, 1, 0, 0)');
 const later=page.locator('.route-card').nth(6);await later.scrollIntoViewIfNeeded();await settled();check('after first six items no stagger delay',await later.evaluate(e=>window.__motionRecords.find(r=>r.node===e)?.delay),0);
 await page.getByPlaceholder('搜索路线标题 / 关键词').fill('motion_no_match_'+Date.now());await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByText('没有找到符合条件的路线',{exact:true}).waitFor();await settled();check('search empty state visible after animation',await page.locator('.empty-state').evaluate(e=>getComputedStyle(e).opacity),'1');
 for(const suffix of ['u','a']){const name='mot_'+Date.now()+suffix;const registered=await(await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,password})})).json();if(registered.code!==200)throw Error('Fixture registration failed');users.push({name,id:Number(sql(`SELECT id FROM sys_user WHERE username='${name}'`))});}
 sql(`UPDATE sys_user SET role='ADMIN' WHERE id=${users[1].id}`);await login(users[0],'/travel-assistant');await page.getByLabel('AI旅行需求',{exact:true}).waitFor();await settled();
 const query='杭州三天自然风光，慢节奏散步';await page.getByLabel('AI旅行需求',{exact:true}).fill(query);await page.getByLabel('API Key',{exact:true}).fill('motion-synthetic-key');await page.evaluate(()=>window.__assistantRoot=document.querySelector('[data-testid="travel-assistant"]'));
 await page.getByRole('tab',{name:'查找已有路线',exact:true}).click();await page.getByLabel('旅行需求',{exact:true}).waitFor();await settled();check('query survives mode animation',await page.getByLabel('旅行需求',{exact:true}).inputValue(),query);
 check('mode does not remount assistant root',await page.evaluate(()=>window.__assistantRoot===document.querySelector('[data-testid="travel-assistant"]')),true);
 await page.getByRole('tab',{name:'AI定制行程',exact:true}).click();await page.getByLabel('AI旅行需求',{exact:true}).waitFor();await settled();check('query returns to AI mode',await page.getByLabel('AI旅行需求',{exact:true}).inputValue(),query);check('mode still clears key as designed',await page.getByLabel('API Key',{exact:true}).inputValue(),'');
 let outcome='done';
 await context.route('**/api/ai/planner/generate-stream',async r=>{
  modelRequests.push('intercepted SSE UI fixture');const {requestId}=r.request().postDataJSON();
  await new Promise(resolve=>setTimeout(resolve,700));
  const frame=(name,data)=>`event:${name}\ndata:${JSON.stringify({requestId,data})}\n\n`;
  const preview={source:'USER_MODEL',model:'motion-ui-fixture',attempts:1,draft:{title:'动效测试预览',answer:'页面动画夹具，非真实模型回答。',dayList:[{title:'第一天',items:[{title:'散步',cost:0}]}]}};
  const end=outcome==='done'?frame('done',preview):outcome==='cancelled'?frame('cancelled',{}):frame('error',{code:3001,message:'UI夹具生成失败'});
  await r.fulfill({status:200,contentType:'text/event-stream',body:frame('progress',{stage:'GENERATING',attempt:1})+end});
 });
 await prepareGeneration();await page.getByRole('button',{name:'生成AI行程',exact:true}).click();await page.locator('.trip-progress-dot').waitFor();
 check('busy progress dot actually loops',await page.locator('.trip-progress-dot').evaluate(e=>getComputedStyle(e).animationIterationCount),'infinite');check('busy disables mode switch',await page.getByRole('tab',{name:'查找已有路线',exact:true}).isDisabled(),true);
 await page.getByTestId('ai-preview').waitFor();await settled();check('completed generation removes progress dot',await page.locator('.trip-progress-dot').count(),0);check('preview stays visible',await page.getByTestId('ai-preview').evaluate(e=>getComputedStyle(e).opacity),'1');check('preview still requires save acknowledgement',await page.getByRole('button',{name:'保存到我的规划并编辑',exact:true}).isDisabled(),true);
 for(const mode of ['cancelled','error']){outcome=mode;await page.getByRole('button',{name:'生成AI行程',exact:true}).click();await page.locator('.trip-progress-dot').waitFor();await page.locator('.trip-progress-dot').waitFor({state:'detached'});check(mode+' stops progress loop',await page.getByTestId('ai-preview').count(),0);}
 const pair=await(await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:users[0].name,password})})).json();if(pair.code!==200)throw Error('Fixture login failed');
 const created=await(await fetch(base+'/api/plan',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+pair.data.accessToken},body:JSON.stringify({title:'动效专属草稿',destinationIds:[],startDate:'2099-01-01',days:1,budget:100,peopleNum:1,status:0,dayList:[{title:'一天',items:[{title:'散步',cost:0}]}]})})).json();check('owned plan fixture created through HTTP',created.code,200);
 await page.locator('nav').getByRole('link',{name:'我的规划',exact:true}).click();await page.locator('.plan-card').waitFor();await settled();await page.locator('.plan-card__main').focus();await settled();check('plan keyboard interaction motion',await page.locator('.plan-card').evaluate(e=>Math.round(new DOMMatrix(getComputedStyle(e).transform).m42)),-3);
 const planLoaded=page.waitForResponse(r=>r.url().endsWith('/api/plan/'+created.data)&&r.request().method()==='GET');await page.keyboard.press('Enter');await page.waitForURL(u=>u.pathname.endsWith('/edit'));check('live editor detail loaded',(await(await planLoaded).json()).code,200);await page.waitForFunction(()=>Array.from(document.querySelectorAll('.el-loading-mask')).every(e=>!e.getClientRects().length));await settled();await page.getByPlaceholder('例如：我的云南 5 日自由行').fill('动画不应清除未保存的规划');await settled();check('plan field remains editable',await page.getByPlaceholder('例如：我的云南 5 日自由行').inputValue(),'动画不应清除未保存的规划');
 await page.setViewportSize({width:390,height:844});await page.goto(base);await settled();await page.getByRole('button',{name:'导航菜单',exact:true}).click();check('mobile navigation opens with CSS animation',await page.locator('#main-navigation').evaluate(e=>getComputedStyle(e).animationName),'trip-soft-enter');await settled();await page.locator('#main-navigation').getByRole('link',{name:'目的地',exact:true}).click();await page.waitForURL(u=>u.pathname==='/destinations');await page.locator('.dest-card').first().waitFor();await settled();check('mobile navigation closes on route change',await page.locator('#main-navigation').isVisible(),false);check('mobile destination no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.goto(base);await homeReady();check('mobile hero fully visible after entry',await page.locator('#home-title').evaluate(e=>getComputedStyle(e).opacity),'1');await page.screenshot({path:path.join(out,'home-mobile.png'),fullPage:true});check('mobile home no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.setViewportSize({width:1440,height:1000});await page.goto(base);await page.waitForFunction(()=>window.__motionRecords.some(r=>r.state==='running'));
 await media('reduce');check('preference change cancels running JS entry',await page.evaluate(()=>window.__motionRecords.filter(r=>r.state==='running').length),0);await page.locator('.route-card').first().scrollIntoViewIfNeeded();await page.locator('.route-card').first().hover();check('reduced motion has no hover movement',await page.locator('.route-card').first().evaluate(e=>getComputedStyle(e).transform),'none');
 const count=await page.evaluate(()=>window.__motionRecords.length);await page.locator('nav').getByRole('link',{name:'目的地',exact:true}).click();await page.waitForURL(u=>u.pathname==='/destinations');await page.locator('.dest-card').first().waitFor();check('reduced navigation starts no JS motion',await page.evaluate(()=>window.__motionRecords.length),count);
 await page.goto(base+'/travel-assistant');await page.getByLabel('AI旅行需求',{exact:true}).waitFor();outcome='done';await prepareGeneration();await page.getByRole('button',{name:'生成AI行程',exact:true}).click();await page.locator('.trip-progress-dot').waitFor();check('reduced progress retains status without pulse',await page.locator('.trip-progress-dot').evaluate(e=>getComputedStyle(e).animationName),'none');await page.getByTestId('ai-preview').waitFor();await settled();check('reduced preview visible',await page.getByTestId('ai-preview').evaluate(e=>getComputedStyle(e).opacity),'1');
 await media('no-preference');const normalBefore=await page.evaluate(()=>window.__motionRecords.length);await page.locator('nav').getByRole('link',{name:'路线',exact:true}).click();await page.locator('.route-card').first().waitFor();await settled();check('restored preference enables entry again',await page.evaluate(()=>window.__motionRecords.length)>normalBefore,true);
 await page.evaluate(()=>localStorage.clear());await login(users[1],'/admin/users');await settled();await page.getByRole('link',{name:'内容批量导入',exact:true}).click();await page.waitForURL(u=>u.pathname==='/admin/import');await settled();check('admin page has entry motion',await page.evaluate(()=>window.__motionRecords.some(r=>r.node.classList.contains('admin-content')&&r.duration===220)),true);
 await page.screenshot({path:path.join(out,'admin-desktop.png'),fullPage:true});await page.goto(base);await homeReady();check('desktop hero fully visible after entry',await page.locator('#home-title').evaluate(e=>getComputedStyle(e).opacity),'1');await page.screenshot({path:path.join(out,'home-desktop.png'),fullPage:true});check('desktop home no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const fallback=await browser.newContext({viewport:{width:390,height:844}});await fallback.addInitScript(()=>{Element.prototype.animate=undefined;window.IntersectionObserver=undefined;});const fallbackPage=await fallback.newPage();await fallbackPage.goto(base);await fallbackPage.locator('.route-card').first().waitFor();check('missing browser APIs leave hero visible',await fallbackPage.locator('#home-title').evaluate(e=>getComputedStyle(e).opacity),'1');check('missing APIs leave catalog visible',await fallbackPage.locator('.route-card').first().evaluate(e=>getComputedStyle(e).opacity),'1');await fallback.close();
 check('unmounted nodes retain no active animation',await page.evaluate(()=>window.__motionRecords.filter(r=>!r.node.isConnected&&r.state==='running').length),0);check('no real model test/generation request',modelRequests.every(s=>s==='intercepted SSE UI fixture'),true);check('motion has no Vue warnings',warnings.length,0);check('no browser exceptions',errors.length,0);phase='COMPLETED';
}catch(e){check('browser completed',e.message,'no error');phase='FAILED';process.exitCode=1;}finally{
 if(browser)await browser.close();
 for(const user of users){sql(`DELETE ui FROM user_plan_item ui JOIN user_plan_day pd ON pd.id=ui.plan_day_id JOIN user_plan p ON p.id=pd.user_plan_id WHERE p.user_id=${user.id}; DELETE pd FROM user_plan_day pd JOIN user_plan p ON p.id=pd.user_plan_id WHERE p.user_id=${user.id}; DELETE FROM user_plan WHERE user_id=${user.id}; DELETE FROM user_preference WHERE user_id=${user.id}; DELETE FROM user_behavior WHERE user_id=${user.id}; DELETE FROM sys_user WHERE id=${user.id}`);cleanSessions(user.id);cleanModelState(user.id);check('owned fixtures removed '+user.id,[sql(`SELECT COUNT(*) FROM sys_user WHERE id=${user.id}`),sql(`SELECT COUNT(*) FROM user_plan WHERE user_id=${user.id}`)],['0','0']);}
 save();console.log(`${checks.filter(c=>c.passed).length}/${checks.length} passed; ${out}`);if(checks.some(c=>!c.passed))process.exitCode=1;
}})();
