// Real two-tab Edge / actual backend refresh; no mocked refresh responses.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const base='http://127.0.0.1:5173',label=process.argv.includes('--final')?'final':'baseline',out=path.resolve(__dirname,'../../docs/dev/evidence/user-finish',new Date().toISOString().replace(/[:.]/g,'-')+'-'+label+'-refresh');
const checks=[],errors=[],users=[],refreshResponses=[];let browser;
function save(){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:'REAL_EDGE_SHARED_STORAGE_REFRESH',label,checks,errors,refreshResponses,users,summary:{total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length}},null,2));}
function check(name,actual,expected){checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
function sql(q){return execFileSync('mysql',['-u','root','-N','-B','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
async function account(){const name='rf_ui_'+crypto.randomUUID().replaceAll('-','').slice(0,10),password='RefreshUi123',u={name,id:null};users.push(u);save();const r=await(await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,password,nickname:name})})).json();if(r.code!==200)throw Error('Registration failed');u.id=Number(sql(`SELECT id FROM sys_user WHERE username='${name}'`));save();return u;}
async function login(p,u){await p.goto(base+'/login?redirect=/user/profile');await p.getByPlaceholder('user1001').fill(u.name);await p.getByPlaceholder('123456',{exact:true}).fill('RefreshUi123');await p.getByRole('button',{name:'登 录',exact:true}).click();await p.waitForURL(x=>x.pathname==='/user/profile');await p.getByLabel('昵称',{exact:true}).waitFor();}
async function requests(p){return p.evaluate(async()=>{const {default:r}=await import('/src/api/request.ts');const results=await Promise.allSettled([r.get('/user/profile'),r.get('/user/stats')]);return results.map(v=>v.status==='fulfilled'?v.value.data.code:'rejected');});}
async function run(){try{
 const u=await account();browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext();const a=await ctx.newPage(),b=await ctx.newPage();for(const p of [a,b]){p.setDefaultTimeout(12000);p.on('pageerror',e=>{errors.push(e.message);save()});p.on('response',async r=>{if(r.url().endsWith('/api/auth/refresh'))try{const data=await r.json();refreshResponses.push({http:r.status(),code:data.code});save()}catch{}})}
 await login(a,u);await b.goto(base+'/user/profile');await b.getByLabel('昵称',{exact:true}).waitFor();
 check('Web Locks available',await a.evaluate(()=>!!navigator.locks),true);
 await a.evaluate(async()=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setToken('invalid-access-for-actual-refresh-test')});
 // Hold both real 401 responses until they exist, making the cross-tab race repeatable.
 let waiting=[];await ctx.route('**/api/user/*',async route=>{if(route.request().headers().authorization==='Bearer invalid-access-for-actual-refresh-test'){const response=await route.fetch();await new Promise(resolve=>{waiting.push(resolve);if(waiting.length===4)waiting.splice(0).forEach(r=>r())});await route.fulfill({response})}else await route.continue()});
 const results=await Promise.all([requests(a),requests(b)]);await ctx.unrouteAll({behavior:'wait'});
 check('all four requests recover',results,[[200,200],[200,200]]);check('only one server refresh rotation',refreshResponses.length,1);check('refresh succeeds',refreshResponses.map(r=>r.code),[200]);
 check('both tabs keep login',await Promise.all([a.evaluate(()=>!!localStorage.getItem('trip_token')),b.evaluate(()=>!!localStorage.getItem('trip_token'))]),[true,true]);
 if(label==='final'){
  check('recovered session actually authenticates',(await requests(a)),[200,200]);
  // Suspend a genuine refresh response, logout, then ensure it cannot repopulate storage.
  let release,arrive;const arrived=new Promise(r=>arrive=r),gate=new Promise(r=>release=r);
  await ctx.route('**/api/auth/refresh',async route=>{const response=await route.fetch();arrive();await gate;await route.fulfill({response})});
  await a.evaluate(async()=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setToken('invalid-access-for-logout-race')});
  const pending=requests(a);await arrived;await b.evaluate(async()=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.clearAuth()});release();check('logout suppresses stale response',await pending,['rejected','rejected']);
  check('logout remains cleared',await a.evaluate(()=>!localStorage.getItem('trip_token')&&!localStorage.getItem('trip_refreshToken')),true);await Promise.all([a.waitForURL(x=>x.pathname==='/login'),b.waitForURL(x=>x.pathname==='/login')]);check('logout closes both protected pages',[new URL(a.url()).pathname,new URL(b.url()).pathname],['/login','/login']);await ctx.unrouteAll({behavior:'wait'});
  // Logging in a different account while old refresh is in flight must also win.
  await login(a,u);await b.goto(base+'/user/profile');const v=await account();const pendingLogin=await(await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:v.name,password:'RefreshUi123'})})).json();
  let release2,arrive2;const arrived2=new Promise(r=>arrive2=r),gate2=new Promise(r=>release2=r);
  await ctx.route('**/api/auth/refresh',async route=>{const response=await route.fetch();arrive2();await gate2;await route.fulfill({response})});
  await a.evaluate(async()=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setToken('invalid-access-for-account-race')});const old=requests(a);await arrived2;
  await b.evaluate(async data=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setSession(data)},pendingLogin.data);release2();check('account switch suppresses stale requests',await old,['rejected','rejected']);
  check('new account preserved',await a.evaluate(()=>JSON.parse(localStorage.getItem('trip_userInfo')).id),v.id);await ctx.unrouteAll({behavior:'wait'});check('new account still authenticates',await requests(a),[200,200]);await a.waitForFunction(name=>document.querySelector('input[aria-label="昵称"]')?.value===name,v.name,{timeout:2000}).catch(()=>{});check('switched account reloads profile fields',await a.getByLabel('昵称',{exact:true}).inputValue(),v.name);
  // A valid legacy token triple migrates through an actual rotation.
  await a.evaluate(async()=>{localStorage.removeItem('trip_authSession');const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setToken('invalid-access-for-legacy-migration')});
  check('legacy login rotates successfully',await requests(a),[200,200]);check('legacy session migrated atomically',await a.evaluate(()=>!!localStorage.getItem('trip_authSession')),true);
  // Same user re-login must also change epoch; userId alone cannot protect it.
  let release3,arrive3;const arrived3=new Promise(r=>arrive3=r),gate3=new Promise(r=>release3=r);
  await ctx.route('**/api/auth/refresh',async route=>{const response=await route.fetch();arrive3();await gate3;await route.fulfill({response})});
  await a.evaluate(async()=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setToken('invalid-access-for-same-account-race')});const oldSame=requests(a);await arrived3;
  const sameLogin=await(await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:v.name,password:'RefreshUi123'})})).json();
  await b.evaluate(async data=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setSession(data)},sameLogin.data);release3();check('same user re-login suppresses stale requests',await oldSame,['rejected','rejected']);
  check('same user new token pair preserved',await a.evaluate(data=>{const s=JSON.parse(localStorage.getItem('trip_authSession'));return s.accessToken===data.accessToken&&s.refreshToken===data.refreshToken},sameLogin.data),true);await ctx.unrouteAll({behavior:'wait'});check('same user new session authenticates',await requests(a),[200,200]);
  // A transport failure is not proof of logout: retain the pair for later retry.
  await a.evaluate(async()=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setToken('invalid-access-for-network-failure')});await ctx.route('**/api/auth/refresh',route=>route.abort('failed'));
  check('refresh network failure rejects requests',await requests(a),['rejected','rejected']);check('network failure retains session',await a.evaluate(()=>!!localStorage.getItem('trip_authSession')),true);await ctx.unrouteAll({behavior:'wait'});check('network recovery refreshes successfully',await requests(a),[200,200]);
  check('login epoch works without randomUUID',await a.evaluate(async()=>{const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts'),old=s.getAuthSession();Object.defineProperty(crypto,'randomUUID',{value:undefined,configurable:true});s.setSession(old);return s.getAuthSession().epoch!==old.epoch}),true);
  check('fallback login epoch keeps authentication',await requests(a),[200,200]);
  // No-lock environments must fail with an explanation rather than rotate unsafely.
  await a.evaluate(async()=>{Object.defineProperty(navigator,'locks',{value:undefined,configurable:true});const s=await import(performance.getEntriesByType('resource').find(e=>new URL(e.name).pathname==='/src/utils/storage.ts')?.name||'/src/utils/storage.ts');s.setToken('invalid-access-for-unsupported-locks')});const before=refreshResponses.length;check('unsupported locks refuses unsafe replay',await requests(a),['rejected','rejected']);check('unsupported locks sends no refresh',refreshResponses.length,before);
 }
 check('no unhandled errors',errors.length,0);
}catch(e){check('refresh run completed',e.message,'no exception')}finally{if(browser)await browser.close();for(const u of users)try{const id=u.id||Number(sql(`SELECT id FROM sys_user WHERE username='${u.name}'`));if(!id)continue;sql(`DELETE FROM sys_user WHERE id=${id} AND username='${u.name}'`);const removed=require('./redis_fixture.cjs').cleanSessions(id);check('fixture sessions removed',require('./redis_fixture.cjs').sessionKeys(id).length,0);check('fixture account removed',sql(`SELECT COUNT(*) FROM sys_user WHERE id=${id}`),'0')}catch(e){check('fixture cleanup',e.name,'no error')}save();console.log(`${checks.filter(c=>c.passed).length}/${checks.length} passed; ${out}`);process.exitCode=checks.every(c=>c.passed)?0:1}}
run();
