// Real Edge/app/MySQL/Redis; localhost:11439 is a controlled provider, not a real model.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const {cleanSessions,cleanModelState}=require('./redis_fixture.cjs');
const base='http://127.0.0.1:5173',password='AssistantUi123',checks=[],errors=[],users=[];
const out=path.resolve(__dirname,'../../docs/dev/evidence/travel-assistant',new Date().toISOString().replace(/[:.]/g,'-')+'-browser');
fs.mkdirSync(out,{recursive:true});let browser,page,phase='RUNNING';
function sql(q){return execFileSync('mysql',['-u','root','-N','-B','--default-character-set=utf8mb4','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
function save(){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:'REAL_EDGE_APP_MYSQL_REDIS_CONTROLLED_PROVIDER',phase,checks,errors,summary:{total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length}},null,2));}
function check(name,actual,expected){checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
async function responseClick(name,endpoint){const r=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST');await page.getByRole('button',{name,exact:true}).click();return (await r).json();}
async function configure(){await page.getByLabel('API基础地址',{exact:true}).fill('http://127.0.0.1:11439/v1');await page.getByLabel('模型名称',{exact:true}).fill('assistant-fixture');await page.getByLabel('API Key',{exact:true}).fill('Bearer controlled-test-key');}
(async()=>{try{
 const name='ta_'+Date.now();const registered=await(await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,password})})).json();if(registered.code!==200)throw Error('Fixture registration failed');users.push({name,id:Number(sql(`SELECT id FROM sys_user WHERE username='${name}'`))});
 browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/login?redirect=/travel-assistant');await page.getByPlaceholder('user1001').fill(name);await page.getByPlaceholder('123456',{exact:true}).fill(password);await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL(u=>u.pathname==='/travel-assistant');await page.getByLabel('API基础地址',{exact:true}).waitFor();
 check('one navigation entry',await page.locator('nav').getByRole('link',{name:'旅行助手',exact:true}).count(),1);check('home not falsely active',await page.locator('nav').getByRole('link',{name:'首页',exact:true}).getAttribute('class').then(s=>s.includes('router-link-active')),false);check('old separate navigation removed',await page.locator('nav').getByRole('link',{name:/旅行推荐|AI规划/}).count(),0);
 check('default public endpoint',await page.getByLabel('API基础地址',{exact:true}).inputValue(),'https://api.deepseek.com');check('default model',await page.getByLabel('模型名称',{exact:true}).inputValue(),'deepseek-flash');check('key starts empty',await page.getByLabel('API Key',{exact:true}).inputValue(),'');
 await page.getByRole('button',{name:'测试连接',exact:true}).click();await page.getByText('请填写模型服务的API Key',{exact:true}).waitFor();check('missing public key stays in UI',await page.getByTestId('model-test-reply').count(),0);
 await configure();const tested=await responseClick('测试连接','/ai/planner/test');check('actual provider final reply',tested.data.reply,'OK');check('reply displayed',await page.getByTestId('model-test-reply').innerText(),'模型回复：OK');
 await page.getByRole('button',{name:'记住地址与模型',exact:true}).click();check('Bearer key not persisted',await page.evaluate(()=>JSON.stringify(localStorage).includes('controlled-test-key')||JSON.stringify(sessionStorage).includes('controlled-test-key')),false);
 const query='杭州一日游，喜欢美食';await page.getByLabel('AI旅行需求',{exact:true}).fill(query);await page.getByRole('tab',{name:/查找已有路线/}).click();check('shared demand goes to route mode',await page.getByLabel('旅行需求',{exact:true}).inputValue(),query);check('route mode needs no key',await page.getByLabel('API Key',{exact:true}).count(),0);
 await page.getByRole('tab',{name:/AI定制行程/}).click();check('demand retained on return',await page.getByLabel('AI旅行需求',{exact:true}).inputValue(),query);check('key erased on mode switch',await page.getByLabel('API Key',{exact:true}).inputValue(),'');await configure();
 await page.getByRole('spinbutton',{name:'AI天数',exact:true}).fill('1');await page.getByRole('spinbutton',{name:'AI天数',exact:true}).press('Tab');
 const finished=page.waitForResponse(r=>r.url().endsWith('/ai/planner/generate-stream'));await page.getByRole('button',{name:'生成AI行程',exact:true}).click();const streamResponse=await finished;check('actual SSE response type',streamResponse.headers()['content-type'].includes('text/event-stream'),true);await page.getByTestId('model-answer').waitFor();check('model text is shown',await page.getByTestId('model-answer').innerText(),'这是受控模型的建议：上午散步，下午休息。<script>window.fixtureXss=true</script>');check('answer HTML is escaped',await page.evaluate(()=>window.fixtureXss===true),false);check('one daily itinerary',await page.locator('.preview .day').count(),1);check('not auto saved',sql(`SELECT COUNT(*) FROM user_plan WHERE user_id=${users[0].id}`),'0');
 await page.waitForFunction(()=>document.querySelectorAll('.el-message').length===0);await page.getByRole('button',{name:'生成AI行程',exact:true}).waitFor();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true,mask:[page.getByLabel('API Key',{exact:true})]});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));check('mobile no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true,mask:[page.getByLabel('API Key',{exact:true})]});
 check('save requires confirmation',await page.getByRole('button',{name:'保存到我的规划并编辑',exact:true}).isDisabled(),true);await page.getByText('我已查看行程，保存为可编辑草稿',{exact:true}).click();await page.getByRole('button',{name:'保存到我的规划并编辑',exact:true}).click();await page.waitForURL(u=>/^\/plan\/\d+\/edit$/.test(u.pathname));check('daily itinerary saved',sql(`SELECT COUNT(*) FROM user_plan WHERE user_id=${users[0].id} AND status=0`),'1');
 await page.goto(base+'/recommend');await page.getByRole('tab',{name:/查找已有路线/}).waitFor();check('old recommendation URL chooses route mode',await page.getByRole('tab',{name:/查找已有路线/}).getAttribute('aria-selected'),'true');check('legacy URL marks unified nav active',await page.locator('nav').getByRole('link',{name:'旅行助手',exact:true}).getAttribute('class').then(s=>s.includes('router-link-active')),true);
 await page.goto(base+'/ai-planner');await page.getByLabel('API基础地址',{exact:true}).waitFor();check('old AI URL chooses AI mode',await page.getByRole('tab',{name:/AI定制行程/}).getAttribute('aria-selected'),'true');check('no key after leaving saved plan',await page.getByLabel('API Key',{exact:true}).inputValue(),'');check('no unhandled browser errors',errors.length,0);phase='COMPLETED';
}catch(e){check('browser completed',e.message,'no error');phase='FAILED';process.exitCode=1;}finally{
 if(browser)await browser.close();for(const user of users){cleanSessions(user.id);cleanModelState(user.id);sql(`DELETE i FROM user_plan_item i JOIN user_plan_day d ON d.id=i.plan_day_id JOIN user_plan p ON p.id=d.user_plan_id WHERE p.user_id=${user.id}; DELETE d FROM user_plan_day d JOIN user_plan p ON p.id=d.user_plan_id WHERE p.user_id=${user.id}; DELETE FROM user_plan WHERE user_id=${user.id}; DELETE FROM llm_call_log WHERE user_id=${user.id}; DELETE FROM user_preference WHERE user_id=${user.id}; DELETE FROM sys_user WHERE id=${user.id}`);check('own fixtures removed',sql(`SELECT COUNT(*) FROM sys_user WHERE id=${user.id}`),'0');}save();console.log(`${checks.filter(c=>c.passed).length}/${checks.length} passed; ${out}`);if(checks.some(c=>!c.passed))process.exitCode=1;
}})();
