// Real Edge profile/preference/recommendation/destination acceptance.
const { chromium }=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/wlky0/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const base='http://127.0.0.1:5173',out=path.resolve(__dirname,'../../docs/dev/evidence/user-finish',new Date().toISOString().replace(/[:.]/g,'-')+'-pages');
const checks=[],errors=[],users=[],routes=[],destinations=[],logs=[];
const marker='FinishUI-'+crypto.randomUUID().slice(0,8),password='FinishUi123';
const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAIAAAASFvFNAAAAFElEQVR4nGOUqzjBAAZMEIqBgQEAGC4BYoYfTS8AAAAASUVORK5CYII=';
let browser,page,stage='start';
function save(){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:'REAL_EDGE_USER_FINISH',stage,checks,errors,fixtures:{users,routes,destinations},httpCodes:logs,summary:{total:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length}},null,2));}
function check(name,actual,expected){checks.push({name,actual,expected,passed:JSON.stringify(actual)===JSON.stringify(expected)});save();}
function sql(q){return execFileSync('mysql',['-u','root','-N','-B','--default-character-set=utf8mb4','trip_llm','-e',q],{encoding:'utf8',env:{...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD||'123456'}}).trim();}
async function call(url,body,method='GET',token=''){const r=await fetch(base+'/api'+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();logs.push({path:url,method,http:r.status,code:data.code});save();return data;}
async function createUser(){const u={name:'finish_'+crypto.randomUUID().replaceAll('-','').slice(0,10),id:null};users.push(u);save();const data=await call('/auth/register',{username:u.name,password,nickname:marker},'POST');if(data.code!==200)throw Error('Registration failed');u.id=Number(sql(`SELECT id FROM sys_user WHERE username='${u.name}'`));save();return u;}
async function choose(label,text){await page.bringToFront();const combo=page.getByRole('combobox',{name:label,exact:true});await combo.focus();await combo.press('ArrowDown');const popup=page.locator('#'+await combo.getAttribute('aria-controls'));await popup.getByRole('option',{name:text,exact:true}).click();await combo.press('Escape');}
async function action(button,ending,method){const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith(ending)&&r.request().method()===method).then(r=>r.json());const [data]=await Promise.all([response,button.click()]);return data;}
async function parse(text){await page.getByLabel('旅行需求',{exact:true}).fill(text);const data=await action(page.getByRole('button',{name:'解析需求',exact:true}),'/api/ai/recommend/intent','POST');check('real intent response',data.code,200);await page.getByTestId('intent-confirm').waitFor();}
async function match(){return action(page.getByRole('button',{name:'确认条件并查找路线',exact:true}),'/api/ai/recommend/match','POST');}
async function screenshot(name){await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0)});await page.waitForTimeout(500);await page.screenshot({path:path.join(out,name),fullPage:true,animations:'disabled'});}
async function run(){try{
 const user=await createUser(),uid=user.id;const auth=await call('/auth/login',{username:user.name,password},'POST'),token=auth.data.accessToken;
 const did=Number(sql(`INSERT INTO destination(name,province,city,longitude,latitude,cover_img,intro,status) VALUES('${marker}','TestProvince','TestCity',120,30,'${image}','Browser destination description',1); SELECT LAST_INSERT_ID()`));destinations.push(did);save();
 const fixtures=[['best',3,200.5,'海滨,康养',1],['rated',3,250,'自然风光',5],['avoid',3,240,'海滨,探险',5],['otherday',5,200,'海滨',5],['off',3,230,'海滨',5]];
 for(const [title,days,price,tags,score]of fixtures){routes.push(Number(sql(`INSERT INTO route(title,destination_id,days,price,tags,avg_score,cover_img,status) VALUES('${marker}-${title}',${did},${days},${price},'${tags}',${score},'${image}',${title==='off'?0:1}); SELECT LAST_INSERT_ID()`)));save();}
 sql(`INSERT INTO attraction(destination_id,name,intro,cover_img,status) VALUES(${did},'Visible attraction','Scenic walk','${image}',1),(${did},'Hidden attraction','Hidden fixture','',0)`);
 browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});page=await ctx.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>{errors.push(e.message);save()});
 await page.goto(base+'/login?redirect=/user/profile');await page.getByPlaceholder('user1001').fill(user.name);await page.getByPlaceholder('123456',{exact:true}).fill(password);await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL(u=>u.pathname==='/user/profile');await page.locator('[data-stat="favoriteCount"] strong').filter({hasText:'0'}).waitFor();
 check('profile shows four statistics',await page.locator('[data-stat]').count(),4);check('new user statistics zero',await page.locator('[data-stat] strong').allTextContents(),['0','0','0','0']);
 await call('/interaction/favorite',{routeId:routes[0]},'POST',token);const when=new Date(Date.now()+864000000).toISOString().slice(0,10);
 await call('/interaction/booking',{routeId:routes[0],travelDate:when,peopleNum:1,contactName:marker,contactPhone:'13800000000'},'POST',token);
 const comment=await call('/interaction/comment',{routeId:routes[0],score:5,content:'User finish browser comment'},'POST',token);
 await call('/plan',{title:marker+' plan',destinationIds:[did],startDate:when,days:1,budget:100,peopleNum:1,status:0,dayList:[{title:'Day one',items:[{title:'Walk',cost:10}]}]},'POST',token);
 const stats=await action(page.getByRole('button',{name:'刷新统计',exact:true}),'/api/user/stats','GET');check('stats HTTP reflects records',stats.data,{favoriteCount:1,bookingCount:1,commentCount:1,planCount:1,chatCount:0});await page.locator('[data-stat="favoriteCount"] strong').filter({hasText:'1'}).waitFor();check('four rendered counts update',await page.locator('[data-stat] strong').allTextContents(),['1','1','1','1']);
 await ctx.setOffline(true);await page.getByRole('button',{name:'刷新统计',exact:true}).click();await page.getByText('统计加载失败，请刷新重试',{exact:true}).waitFor();check('stats network failure explained',true,true);await ctx.setOffline(false);check('stats retry restores response',(await action(page.getByRole('button',{name:'刷新统计',exact:true}),'/api/user/stats','GET')).code,200);
 await page.getByLabel('手机号',{exact:true}).fill('123');check('invalid profile phone has actual rejection',(await action(page.getByRole('button',{name:'保存资料',exact:true}),'/api/user/profile','PUT')).code,400);await page.getByText('手机号格式不正确',{exact:true}).waitFor();
 stage='preference';save();await page.goto(base+'/user/preference');await page.getByLabel('预算上限',{exact:true}).waitFor();await page.locator('.el-loading-mask').waitFor({state:'hidden'});
 await page.getByLabel('预算下限',{exact:true}).fill('300');await page.getByLabel('预算上限',{exact:true}).fill('200');await page.getByRole('button',{name:'保存偏好',exact:true}).click();await page.getByText('预算下限必须小于上限',{exact:true}).waitFor();check('invalid preference range explained',true,true);
 await page.getByLabel('预算下限',{exact:true}).fill('150.50');await page.getByLabel('预算上限',{exact:true}).fill('300.50');await page.getByLabel('常用天数',{exact:true}).fill('3');await choose('偏好标签','海滨');await choose('偏好标签','康养');await choose('避雷标签','探险');
 const prefs=await action(page.getByRole('button',{name:'保存偏好',exact:true}),'/api/user/preference','PUT');check('preference saved via page',prefs.code,200);check('preference decimals persisted',[prefs.data.budgetMin,prefs.data.budgetMax],[150.5,300.5]);await page.reload();await page.locator('.el-loading-mask').waitFor({state:'hidden'});check('saved preference reloads days',Number(await page.getByLabel('常用天数',{exact:true}).inputValue()),3);
 await ctx.setOffline(true);await page.getByRole('button',{name:'刷新偏好',exact:true}).click();await page.getByText('偏好加载失败，请重试后再编辑',{exact:true}).waitFor();check('failed preference load blocks saving',await page.getByRole('button',{name:'保存偏好',exact:true}).isDisabled(),true);await ctx.setOffline(false);check('preference load recovers',(await action(page.getByRole('button',{name:'刷新偏好',exact:true}),'/api/user/preference','GET')).code,200);
 stage='recommend';save();await page.goto(base+'/recommend');await page.getByRole('button',{name:'解析需求',exact:true}).waitFor();await page.getByRole('button',{name:'解析需求',exact:true}).waitFor({state:'visible'});await parse('我想了解旅行路线');
 check('saved days prefilled',Number(await page.getByLabel('旅行天数',{exact:true}).inputValue()),3);check('saved decimal bounds prefilled',[Number(await page.getByLabel('预算下限',{exact:true}).inputValue()),Number(await page.getByLabel('预算上限',{exact:true}).inputValue())],[150.5,300.5]);check('saved origins shown',await page.getByTestId('saved-preference-note').isVisible(),true);
 await page.getByLabel('目的地',{exact:true}).fill(marker);let matched=await match();check('saved preference actual route ordering',matched.data.list.map(r=>r.routeId),routes.slice(0,2));await page.getByTestId('match-results').waitFor();check('two matching cards render',await page.locator('.match-card').count(),2);check('effective budget visible',(await page.getByTestId('effective-criteria').innerText()).includes('150.5—300.5'),true);
 await page.locator('label.el-checkbox').filter({hasText:'参考已保存偏好'}).click();check('saved preference switch disabled',await page.getByRole('checkbox',{name:'参考已保存偏好',exact:true}).isChecked(),false);matched=await match();check('opt out removes default filters',matched.data.totalCandidates,4);
 await page.locator('label.el-checkbox').filter({hasText:'参考已保存偏好'}).click();await page.getByLabel('旅行天数',{exact:true}).fill('');await page.getByLabel('旅行天数',{exact:true}).press('Tab');await page.getByLabel('预算下限',{exact:true}).fill('');await page.getByLabel('预算下限',{exact:true}).press('Tab');await page.getByLabel('预算上限',{exact:true}).fill('');await page.getByLabel('预算上限',{exact:true}).press('Tab');await choose('偏好标签','海滨');await choose('偏好标签','康养');await choose('排除标签','探险');matched=await match();check('explicit clear is not refilled',matched.data.totalCandidates,4);check('explicit clear reflected by server',[matched.data.effectiveCriteria.days,matched.data.effectiveCriteria.budgetMin,matched.data.effectiveCriteria.budgetMax,matched.data.effectiveCriteria.preferenceTags,matched.data.effectiveCriteria.avoid],[null,null,null,[],[]]);
 await parse('我想玩5天，预算500元，喜欢美食');await page.getByLabel('目的地',{exact:true}).fill(marker);matched=await match();check('explicit query conditions win over saved defaults',[matched.data.effectiveCriteria.days,matched.data.effectiveCriteria.budgetMin,matched.data.effectiveCriteria.budgetMax,matched.data.effectiveCriteria.preferenceTags],[5,null,500,['美食']]);check('explicit request gets correct route',matched.data.list.map(r=>r.routeId),[routes[3]]);
 await page.setViewportSize({width:390,height:844});await screenshot('recommend-mobile.png');check('mobile recommendation has no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
 stage='destination';save();await page.goto(base+'/destination/'+did);await page.getByRole('heading',{name:marker,exact:true}).waitFor();check('only active attraction shown',await page.getByRole('heading',{name:'Visible attraction',exact:true}).count(),1);check('hidden attraction absent',await page.getByRole('heading',{name:'Hidden attraction',exact:true}).count(),0);check('only public routes in destination',await page.locator('.routes .route-card').count(),4);check('mobile destination has no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:path.join(out,'destination-mobile.png'),fullPage:true,animations:'disabled'});
 sql(`UPDATE destination SET status=0 WHERE id=${did}`);await page.reload();await page.getByText('目的地不存在、已下架或暂时无法加载',{exact:true}).waitFor();check('offline destination removes old detail',await page.getByRole('heading',{name:marker,exact:true}).count(),0);sql(`UPDATE destination SET status=1 WHERE id=${did}`);await page.getByRole('button',{name:'重新加载',exact:true}).click();await page.getByRole('heading',{name:marker,exact:true}).waitFor();check('destination retry works',true,true);
 await page.goto(base+'/user/profile');await page.locator('[data-stat="planCount"] strong').filter({hasText:'1'}).waitFor();check('profile mobile has no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:path.join(out,'profile-mobile.png'),fullPage:true,animations:'disabled'});await call('/interaction/comment/'+comment.data.id,undefined,'DELETE',token);const changed=await action(page.getByRole('button',{name:'刷新统计',exact:true}),'/api/user/stats','GET');check('deleted comment changes statistics',changed.data.commentCount,0);
 await page.goto(base+'/user/preference');await page.locator('.el-loading-mask').waitFor({state:'hidden'});check('preference mobile has no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:path.join(out,'preference-mobile.png'),fullPage:true,animations:'disabled'});
}catch(e){check('browser execution completed',e.message,'no exception');if(page)try{await page.screenshot({path:path.join(out,'failure.png'),fullPage:true})}catch{}}
finally{if(browser)await browser.close();try{
 for(const u of users){const id=u.id||Number(sql(`SELECT id FROM sys_user WHERE username='${u.name}'`));if(!id)continue;sql(`DELETE i FROM user_plan_item i JOIN user_plan_day d ON d.id=i.plan_day_id JOIN user_plan p ON p.id=d.user_plan_id WHERE p.user_id=${id}; DELETE d FROM user_plan_day d JOIN user_plan p ON p.id=d.user_plan_id WHERE p.user_id=${id}; DELETE FROM user_plan WHERE user_id=${id}; DELETE FROM route_comment_like WHERE user_id=${id}; DELETE FROM route_comment WHERE user_id=${id}; DELETE FROM route_booking WHERE user_id=${id}; DELETE FROM route_like WHERE user_id=${id}; DELETE FROM route_favorite WHERE user_id=${id}; DELETE FROM user_behavior WHERE user_id=${id}; DELETE FROM user_preference WHERE user_id=${id}; DELETE FROM llm_call_log WHERE user_id=${id}; DELETE FROM sys_user WHERE id=${id} AND username='${u.name}'`);const removed=require('./redis_fixture.cjs').cleanSessions(id);check('fixture sessions removed',require('./redis_fixture.cjs').sessionKeys(id).length,0);check('fixture user removed',sql(`SELECT COUNT(*) FROM sys_user WHERE id=${id}`),'0');}
 for(const id of routes)sql(`DELETE FROM route WHERE id=${id}`);for(const id of destinations)sql(`DELETE FROM attraction WHERE destination_id=${id}; DELETE FROM destination WHERE id=${id}`);check('fixture content removed',true,true);
}catch(e){check('fixture cleanup',e.message,'no exception')}
check('no unhandled browser errors',errors.length,0);save();console.log(`${checks.filter(c=>c.passed).length}/${checks.length} passed; ${out}`);process.exitCode=checks.every(c=>c.passed)?0:1;}}
run();
